@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/des/rand_key.c.html#601]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/des/rand_key.c.html#606]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/des/rand_key.c.html#613]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/des/rand_key.c.html#775]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/des/rand_key.c.html#790]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/des/rand_key.c.html#800]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/des/rand_key.c.html#812]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/des/rand_key.c.html#818]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/des/rand_key.c.html#824]]]
} 
@enduml
