@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#837]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#842]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#849]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/core_fetch.c.html#1011]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/core_fetch.c.html#1026]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/core_fetch.c.html#1036]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/core_fetch.c.html#1048]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/core_fetch.c.html#1054]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/core_fetch.c.html#1060]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1728]]]
} 
@enduml
