@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#442]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#444]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#447]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#837]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#842]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#849]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/core_fetch.c.html#1011]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/core_fetch.c.html#1026]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/core_fetch.c.html#1036]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/core_fetch.c.html#1048]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/core_fetch.c.html#1054]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/core_fetch.c.html#1060]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1728]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
realpath(char*;char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../.././qc/crypto/core_fetch.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../.././qc/crypto/core_fetch.c.html#1]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
memcpy(void*;void*;size_t) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
memmove(void*;void*;size_t) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
memset(void*;int;size_t) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
strcpy(char*;char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
stpcpy(char*;char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
strncpy(char*;char*;size_t) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
stpncpy(char*;char*;size_t) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
strcat(char*;char*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
strncat(char*;char*;size_t) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
getchar(void) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fgetc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
getc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
getchar_unlocked(void) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
putchar(int) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fputc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
putc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
putchar_unlocked(int) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fprintf(FILE*;char*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
printf(char*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
dprintf(int;char*) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fgets(char*;int;FILE*) :  char  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/core_fetch.c.html#1]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/core_fetch.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/core_fetch.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/core_fetch.c.html#1]]]
} 
@enduml
