@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/getenv.c.html#327]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/getenv.c.html#332]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/getenv.c.html#339]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/getenv.c.html#671]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/getenv.c.html#686]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/getenv.c.html#696]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/getenv.c.html#708]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/getenv.c.html#714]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/getenv.c.html#720]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/crypto/getenv.c.html#1432]]]
} 
@enduml
