@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/o_fopen.c.html#501]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/o_fopen.c.html#506]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/o_fopen.c.html#513]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/o_fopen.c.html#679]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/o_fopen.c.html#694]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/o_fopen.c.html#704]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/o_fopen.c.html#716]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/o_fopen.c.html#722]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/o_fopen.c.html#728]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/crypto/o_fopen.c.html#1393]]]
} 
@enduml
