@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/params_from_text.c.html#169]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/params_from_text.c.html#174]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/params_from_text.c.html#181]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/params_from_text.c.html#481]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/params_from_text.c.html#496]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/params_from_text.c.html#506]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/params_from_text.c.html#518]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/params_from_text.c.html#524]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/params_from_text.c.html#530]]]
} 
@enduml
