@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/provider_predefined.c.html#439]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/provider_predefined.c.html#441]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/provider_predefined.c.html#444]]]
sk_INFOPAIR_num(structstack_st_INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_value(structstack_st_INFOPAIR*;int) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_new(sk_INFOPAIR_compfunc) :  struct stack_st_INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_new_null(void) :  struct stack_st_INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_new_reserve(sk_INFOPAIR_compfunc;int) :  struct stack_st_INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_reserve(structstack_st_INFOPAIR*;int) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_free(structstack_st_INFOPAIR*) :  void  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_zero(structstack_st_INFOPAIR*) :  void  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_delete(structstack_st_INFOPAIR*;int) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_delete_ptr(structstack_st_INFOPAIR*;INFOPAIR*) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_push(structstack_st_INFOPAIR*;INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_unshift(structstack_st_INFOPAIR*;INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_pop(structstack_st_INFOPAIR*) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_shift(structstack_st_INFOPAIR*) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_pop_free(structstack_st_INFOPAIR*;sk_INFOPAIR_freefunc) :  void  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_insert(structstack_st_INFOPAIR*;INFOPAIR*;int) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_set(structstack_st_INFOPAIR*;int;INFOPAIR*) : INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_find(structstack_st_INFOPAIR*;INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_find_ex(structstack_st_INFOPAIR*;INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_find_all(structstack_st_INFOPAIR*;INFOPAIR*;int*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_sort(structstack_st_INFOPAIR*) :  void  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_is_sorted(structstack_st_INFOPAIR*) :  int  [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_dup(structstack_st_INFOPAIR*) :  struct stack_st_INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_deep_copy(structstack_st_INFOPAIR*;sk_INFOPAIR_copyfunc;sk_INFOPAIR_freefunc) :  struct stack_st_INFOPAIR [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
sk_INFOPAIR_set_cmp_func(structstack_st_INFOPAIR*;sk_INFOPAIR_compfunc) : sk_INFOPAIR_compfunc [[[./../.././qc/crypto/provider_predefined.c.html#707]]]
} 
@enduml
