@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../.././qc/crypto/punycode.c.html#754]]]
fgetc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/punycode.c.html#763]]]
getc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/punycode.c.html#773]]]
getchar_unlocked(void) :  int  [[[./../.././qc/crypto/punycode.c.html#780]]]
putchar(int) :  int  [[[./../.././qc/crypto/punycode.c.html#789]]]
fputc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/punycode.c.html#798]]]
putc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/punycode.c.html#808]]]
putchar_unlocked(int) :  int  [[[./../.././qc/crypto/punycode.c.html#815]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#821]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#828]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#847]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#860]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#879]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#893]]]
fprintf(FILE*;char*) :  int  [[[./../.././qc/crypto/punycode.c.html#914]]]
printf(char*) :  int  [[[./../.././qc/crypto/punycode.c.html#921]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/punycode.c.html#933]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/punycode.c.html#943]]]
dprintf(int;char*) :  int  [[[./../.././qc/crypto/punycode.c.html#958]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/punycode.c.html#969]]]
fgets(char*;int;FILE*) :  char  [[[./../.././qc/crypto/punycode.c.html#988]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/punycode.c.html#1014]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/punycode.c.html#1041]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1368]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1373]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1380]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/punycode.c.html#1527]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/punycode.c.html#1542]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/punycode.c.html#1552]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/punycode.c.html#1564]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/punycode.c.html#1570]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/punycode.c.html#1576]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/crypto/punycode.c.html#2244]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
realpath(char*;char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../.././qc/crypto/punycode.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../.././qc/crypto/punycode.c.html#1]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
memcpy(void*;void*;size_t) :  void  [[[./../.././qc/crypto/punycode.c.html#1]]]
memmove(void*;void*;size_t) :  void  [[[./../.././qc/crypto/punycode.c.html#1]]]
memset(void*;int;size_t) :  void  [[[./../.././qc/crypto/punycode.c.html#1]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
strcpy(char*;char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
stpcpy(char*;char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
strncpy(char*;char*;size_t) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
stpncpy(char*;char*;size_t) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
strcat(char*;char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
strncat(char*;char*;size_t) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../.././qc/crypto/punycode.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
read(int;void*;size_t) : ssize_t [[[./../.././qc/crypto/punycode.c.html#1]]]
pread(int;void*;size_t;__off_t) : ssize_t [[[./../.././qc/crypto/punycode.c.html#1]]]
readlink(char*;char*;size_t) : ssize_t [[[./../.././qc/crypto/punycode.c.html#1]]]
readlinkat(int;char*;char*;size_t) : ssize_t [[[./../.././qc/crypto/punycode.c.html#1]]]
getcwd(char*;size_t) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
getwd(char*) :  char  [[[./../.././qc/crypto/punycode.c.html#1]]]
confstr(int;char*;size_t) : size_t [[[./../.././qc/crypto/punycode.c.html#1]]]
getgroups(int;__gid_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
ttyname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
getlogin_r(char*;size_t) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
gethostname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
getdomainname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_ends_with_dirsep(char*) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_is_absolute_path(char*) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
adapt(unsignedint;unsignedint;unsignedint) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
is_basic(unsignedint) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
digit_decoded(unsignedchar) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_punycode_decode(char*;size_t;unsignedint*;unsignedint*) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
codepoint2utf8(unsignedchar*;unsignedlong) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_a2ulabel(char*;char*;size_t*) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
ossl_a2ucompare(char*;char*) :  int  [[[./../.././qc/crypto/punycode.c.html#1]]]
} 
@enduml
