@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/quic_vlint.c.html#504]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/quic_vlint.c.html#509]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/quic_vlint.c.html#516]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/quic_vlint.c.html#678]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/quic_vlint.c.html#693]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/quic_vlint.c.html#703]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/quic_vlint.c.html#715]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/quic_vlint.c.html#721]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/quic_vlint.c.html#727]]]
} 
@enduml
