@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../.././qc/crypto/time.c.html#931]]]
fgetc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/time.c.html#940]]]
getc_unlocked(FILE*) :  int  [[[./../.././qc/crypto/time.c.html#950]]]
getchar_unlocked(void) :  int  [[[./../.././qc/crypto/time.c.html#957]]]
putchar(int) :  int  [[[./../.././qc/crypto/time.c.html#966]]]
fputc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/time.c.html#975]]]
putc_unlocked(int;FILE*) :  int  [[[./../.././qc/crypto/time.c.html#985]]]
putchar_unlocked(int) :  int  [[[./../.././qc/crypto/time.c.html#992]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#998]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1005]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1024]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1037]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1056]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1070]]]
fprintf(FILE*;char*) :  int  [[[./../.././qc/crypto/time.c.html#1091]]]
printf(char*) :  int  [[[./../.././qc/crypto/time.c.html#1098]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/time.c.html#1110]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/time.c.html#1120]]]
dprintf(int;char*) :  int  [[[./../.././qc/crypto/time.c.html#1135]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../.././qc/crypto/time.c.html#1146]]]
fgets(char*;int;FILE*) :  char  [[[./../.././qc/crypto/time.c.html#1165]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/time.c.html#1191]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../.././qc/crypto/time.c.html#1218]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1378]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1383]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/crypto/time.c.html#1390]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/crypto/time.c.html#1537]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/crypto/time.c.html#1552]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/crypto/time.c.html#1562]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/crypto/time.c.html#1574]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/crypto/time.c.html#1580]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/crypto/time.c.html#1586]]]
} 
@enduml
