@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#298]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#305]]]
memcpy(void*;void*;size_t) :  void  [[[./../.././qc/apps/cmp.c.html#346]]]
memmove(void*;void*;size_t) :  void  [[[./../.././qc/apps/cmp.c.html#354]]]
memset(void*;int;size_t) :  void  [[[./../.././qc/apps/cmp.c.html#361]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#374]]]
strcpy(char*;char*) :  char  [[[./../.././qc/apps/cmp.c.html#381]]]
stpcpy(char*;char*) :  char  [[[./../.././qc/apps/cmp.c.html#388]]]
strncpy(char*;char*;size_t) :  char  [[[./../.././qc/apps/cmp.c.html#396]]]
stpncpy(char*;char*;size_t) :  char  [[[./../.././qc/apps/cmp.c.html#406]]]
strcat(char*;char*) :  char  [[[./../.././qc/apps/cmp.c.html#413]]]
strncat(char*;char*;size_t) :  char  [[[./../.././qc/apps/cmp.c.html#420]]]
tolower(int) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#640]]]
toupper(int) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#646]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#1009]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#1014]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../.././qc/apps/cmp.c.html#1021]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../.././qc/apps/cmp.c.html#1177]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../.././qc/apps/cmp.c.html#1192]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../.././qc/apps/cmp.c.html#1202]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../.././qc/apps/cmp.c.html#1214]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../.././qc/apps/cmp.c.html#1220]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../.././qc/apps/cmp.c.html#1226]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../.././qc/apps/cmp.c.html#1894]]]
} 
@enduml
