@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#928]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#937]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#947]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#954]]]
putchar(int) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#963]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#972]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#982]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#989]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#995]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1002]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1021]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1034]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1053]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1067]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1088]]]
printf(char*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1095]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1107]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1117]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1132]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1143]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/ec/ec_backend.c.html#1162]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1188]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1215]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1388]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1393]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_backend.c.html#1400]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1547]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1562]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1572]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1584]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1590]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ec_backend.c.html#1596]]]
} 
@enduml
