@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#901]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#910]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#920]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#927]]]
putchar(int) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#936]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#945]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#955]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#962]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#968]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#975]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#994]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1007]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1026]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1040]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1061]]]
printf(char*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1068]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1080]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1090]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1105]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1116]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/ec/ec_err.c.html#1135]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1161]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1188]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1348]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1353]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1360]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1507]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1522]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1532]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1544]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1550]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1556]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/ec/ec_err.c.html#2224]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_BIO_type(BIO*) : BIO [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_BIO_compfunc_type(sk_BIO_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_BIO_freefunc_type(sk_BIO_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_compfunc_type(lh_OPENSSL_STRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_hashfunc_type(lh_OPENSSL_STRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_doallfunc_type(lh_OPENSSL_STRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_compfunc_type(lh_OPENSSL_CSTRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_hashfunc_type(lh_OPENSSL_CSTRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_doallfunc_type(lh_OPENSSL_CSTRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ERR_GET_LIB(unsignedlong) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ERR_GET_RFLAGS(unsignedlong) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ERR_GET_REASON(unsignedlong) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ERR_FATAL_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ERR_COMMON_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_compfunc_type(lh_ERR_STRING_DATA_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_hashfunc_type(lh_ERR_STRING_DATA_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_doallfunc_type(lh_ERR_STRING_DATA_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
ossl_err_load_EC_strings(void) :  int  [[[./../../.././qc/crypto/ec/ec_err.c.html#1]]]
} 
@enduml
