@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#325]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#332]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#373]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#381]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#388]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#401]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#408]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#415]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#423]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#433]]]
strcat(char*;char*) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#440]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#447]]]
getchar(void) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1304]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1313]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1323]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1330]]]
putchar(int) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1339]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1348]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1358]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1365]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1371]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1378]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1397]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1410]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1429]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1443]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1464]]]
printf(char*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1471]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1483]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1493]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1508]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1519]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1538]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1564]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1591]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1751]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1756]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1763]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1910]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1925]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1935]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1947]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1953]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ec/ecdsa_ossl.c.html#1959]]]
} 
@enduml
