@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rand/prov_seed.c.html#195]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rand/prov_seed.c.html#200]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rand/prov_seed.c.html#207]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#507]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#522]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#532]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#544]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#550]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/rand/prov_seed.c.html#556]]]
} 
@enduml
