@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/rand/rand_err.c.html#901]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/rand/rand_err.c.html#910]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/rand/rand_err.c.html#920]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/rand/rand_err.c.html#927]]]
putchar(int) :  int  [[[./../../.././qc/crypto/rand/rand_err.c.html#936]]]
} 
@enduml
