@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#200]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#205]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#212]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#512]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#527]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#537]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#549]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#555]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#561]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/rsa/rsa_ossl.c.html#1229]]]
} 
@enduml
