@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#914]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#923]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#933]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#940]]]
putchar(int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#949]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#958]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#968]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#975]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#981]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#988]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1007]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1020]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1039]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1053]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1074]]]
printf(char*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1081]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1093]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1103]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1118]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1129]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1148]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1174]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1201]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1374]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1379]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1386]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1533]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1548]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1558]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1570]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1576]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1582]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#2250]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_BIO_type(BIO*) : BIO [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_BIO_compfunc_type(sk_BIO_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_BIO_freefunc_type(sk_BIO_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_X509_ALGOR_type(X509_ALGOR*) : X509_ALGOR [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_X509_ALGOR_compfunc_type(sk_X509_ALGOR_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_X509_ALGOR_copyfunc_type(sk_X509_ALGOR_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_X509_ALGOR_freefunc_type(sk_X509_ALGOR_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_type(ASN1_STRING_TABLE*) : ASN1_STRING_TABLE [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_compfunc_type(sk_ASN1_STRING_TABLE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_copyfunc_type(sk_ASN1_STRING_TABLE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_freefunc_type(sk_ASN1_STRING_TABLE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_TYPE_type(ASN1_TYPE*) : ASN1_TYPE [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_TYPE_compfunc_type(sk_ASN1_TYPE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_TYPE_copyfunc_type(sk_ASN1_TYPE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_TYPE_freefunc_type(sk_ASN1_TYPE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_OBJECT_type(ASN1_OBJECT*) : ASN1_OBJECT [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_OBJECT_compfunc_type(sk_ASN1_OBJECT_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_OBJECT_copyfunc_type(sk_ASN1_OBJECT_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_OBJECT_freefunc_type(sk_ASN1_OBJECT_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_INTEGER_type(ASN1_INTEGER*) : ASN1_INTEGER [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_INTEGER_compfunc_type(sk_ASN1_INTEGER_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_INTEGER_copyfunc_type(sk_ASN1_INTEGER_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_INTEGER_freefunc_type(sk_ASN1_INTEGER_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_UTF8STRING_type(ASN1_UTF8STRING*) : ASN1_UTF8STRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_UTF8STRING_compfunc_type(sk_ASN1_UTF8STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_UTF8STRING_copyfunc_type(sk_ASN1_UTF8STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_UTF8STRING_freefunc_type(sk_ASN1_UTF8STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_type(ASN1_GENERALSTRING*) : ASN1_GENERALSTRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_compfunc_type(sk_ASN1_GENERALSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_copyfunc_type(sk_ASN1_GENERALSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_freefunc_type(sk_ASN1_GENERALSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_num(structstack_st_nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_value(structstack_st_nid_triple*;int) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_new(sk_nid_triple_compfunc) :  struct stack_st_nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_new_null(void) :  struct stack_st_nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_new_reserve(sk_nid_triple_compfunc;int) :  struct stack_st_nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_reserve(structstack_st_nid_triple*;int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_free(structstack_st_nid_triple*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_zero(structstack_st_nid_triple*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_delete(structstack_st_nid_triple*;int) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_delete_ptr(structstack_st_nid_triple*;nid_triple*) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_push(structstack_st_nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_unshift(structstack_st_nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_pop(structstack_st_nid_triple*) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_shift(structstack_st_nid_triple*) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_pop_free(structstack_st_nid_triple*;sk_nid_triple_freefunc) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_insert(structstack_st_nid_triple*;nid_triple*;int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_set(structstack_st_nid_triple*;int;nid_triple*) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_find(structstack_st_nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_find_ex(structstack_st_nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_find_all(structstack_st_nid_triple*;nid_triple*;int*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_sort(structstack_st_nid_triple*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_is_sorted(structstack_st_nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_dup(structstack_st_nid_triple*) :  struct stack_st_nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_deep_copy(structstack_st_nid_triple*;sk_nid_triple_copyfunc;sk_nid_triple_freefunc) :  struct stack_st_nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sk_nid_triple_set_cmp_func(structstack_st_nid_triple*;sk_nid_triple_compfunc) : sk_nid_triple_compfunc [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_compfunc_type(lh_OPENSSL_STRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_hashfunc_type(lh_OPENSSL_STRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_doallfunc_type(lh_OPENSSL_STRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_compfunc_type(lh_OPENSSL_CSTRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_hashfunc_type(lh_OPENSSL_CSTRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_doallfunc_type(lh_OPENSSL_CSTRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ERR_GET_LIB(unsignedlong) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ERR_GET_RFLAGS(unsignedlong) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ERR_GET_REASON(unsignedlong) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ERR_FATAL_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ERR_COMMON_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_compfunc_type(lh_ERR_STRING_DATA_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_hashfunc_type(lh_ERR_STRING_DATA_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_doallfunc_type(lh_ERR_STRING_DATA_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sig_cmp(nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sig_cmp_BSEARCH_CMP_FN(void*;void*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_bsearch_sig(nid_triple*;nid_triple*;int) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sig_sk_cmp(nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sigx_cmp(nid_triple*;nid_triple*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sigx_cmp_BSEARCH_CMP_FN(void*;void*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_bsearch_sigx(nid_triple*;nid_triple*;int) : nid_triple [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
o_sig_init_ossl_(void) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
o_sig_init(void) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
obj_sig_init(void) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
ossl_obj_find_sigid_algs(int;int*;int*;int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_find_sigid_algs(int;int*;int*) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_find_sigid_by_algs(int*;int;int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_add_sigid(int;int;int) :  int  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
sid_free(nid_triple*) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
OBJ_sigid_free(void) :  void  [[[./../../.././qc/crypto/objects/obj_xref.c.html#1]]]
} 
@enduml
