@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#769]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#778]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#788]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#795]]]
putchar(int) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#804]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#813]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#823]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#830]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#836]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#843]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#862]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#875]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#894]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#908]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#929]]]
printf(char*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#936]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#948]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#958]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#973]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#984]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1003]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1029]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1056]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1343]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1345]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1348]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1674]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1679]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1686]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1833]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1848]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1858]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1870]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1876]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/dh/dh_ameth.c.html#1882]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/dh/dh_ameth.c.html#2550]]]
} 
@enduml
