@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#898]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#907]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#917]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#924]]]
putchar(int) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#933]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#942]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#952]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#959]]]
getline(char*;size_t*;FILE*) : __ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#969]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#979]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#986]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1005]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1018]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1037]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1051]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1072]]]
printf(char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1079]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1091]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1101]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1116]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1127]]]
asprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1153]]]
__asprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1160]]]
obstack_printf(structobstack*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1168]]]
vasprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1176]]]
obstack_vprintf(structobstack*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1183]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1204]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1230]]]
fgets_unlocked(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1256]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1285]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1872]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1877]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1884]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2053]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2068]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2078]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2090]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2096]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2102]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2814]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
read(int;void*;size_t) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
pread(int;void*;size_t;__off_t) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
pread64(int;void*;size_t;__off64_t) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
readlink(char*;char*;size_t) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
readlinkat(int;char*;char*;size_t) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
getcwd(char*;size_t) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
getwd(char*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
confstr(int;char*;size_t) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
getgroups(int;__gid_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ttyname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
getlogin_r(char*;size_t) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
gethostname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
getdomainname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_ticks2time(uint64_t) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time2ticks(OSSL_TIME) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_zero(void) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_infinite(void) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_to_timeval(OSSL_TIME) :  struct timeval [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_from_timeval(structtimeval) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_to_time_t(OSSL_TIME) : time_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_from_time_t(time_t) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_compare(OSSL_TIME;OSSL_TIME) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_is_zero(OSSL_TIME) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_is_infinite(OSSL_TIME) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_add_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_sub_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_mul_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_div_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_mod_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_div_round_up_time(uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_muldiv_time(uint64_t;uint64_t;uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_neg_time(uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
safe_abs_time(uint64_t;int*) : uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_add(OSSL_TIME;OSSL_TIME) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_subtract(OSSL_TIME;OSSL_TIME) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_abs_difference(OSSL_TIME;OSSL_TIME) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_multiply(OSSL_TIME;uint64_t) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_divide(OSSL_TIME;uint64_t) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_muldiv(OSSL_TIME;uint64_t;uint64_t) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_max(OSSL_TIME;OSSL_TIME) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
ossl_time_min(OSSL_TIME;OSSL_TIME) : OSSL_TIME [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
__cmsg_nxthdr(structmsghdr*;structcmsghdr*) :  struct cmsghdr [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
recv(int;void*;size_t;int) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
recvfrom(int;void*;size_t;int;__SOCKADDR_ARG;socklen_t*) : ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1]]]
} 
@enduml
