@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#898]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#907]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#917]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#924]]]
putchar(int) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#933]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#942]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#952]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#959]]]
getline(char*;size_t*;FILE*) : __ssize_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#969]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#979]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#986]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1005]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1018]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1037]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1051]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1072]]]
printf(char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1079]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1091]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1101]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1116]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1127]]]
asprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1153]]]
__asprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1160]]]
obstack_printf(structobstack*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1168]]]
vasprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1176]]]
obstack_vprintf(structobstack*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1183]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1204]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1230]]]
fgets_unlocked(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1256]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1285]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1872]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1877]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bio/bss_dgram.c.html#1884]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2053]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2068]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2078]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2090]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2096]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bio/bss_dgram.c.html#2102]]]
} 
@enduml
