@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#672]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#677]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#684]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#878]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#893]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#903]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#915]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#921]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#927]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../../.././qc/providers/implementations/rands/seeding/rand_unix.c.html#1639]]]
} 
@enduml
