@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#917]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#926]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#936]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#943]]]
putchar(int) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#952]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#961]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#971]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#978]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#984]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#991]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1010]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1023]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1042]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1056]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1077]]]
printf(char*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1084]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1096]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1106]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1121]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1132]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1151]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1177]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1204]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1377]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1382]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1389]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1536]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1551]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1561]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1573]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1579]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#1585]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/ocsp/ocsp_http.c.html#2253]]]
} 
@enduml
