@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#167]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#172]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#179]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#479]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#494]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#504]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#516]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#522]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#528]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/implementations/rands/drbg_hash.c.html#1196]]]
} 
@enduml
