@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#485]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#487]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#490]]]
getchar(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1323]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1332]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1342]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1349]]]
putchar(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1358]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1367]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1377]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1384]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1390]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1397]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1416]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1429]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1448]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1462]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1483]]]
printf(char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1490]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1502]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1512]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1527]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1538]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1557]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1583]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1610]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1781]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1786]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1793]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1940]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1955]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1965]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1977]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1983]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1989]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#2657]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_rc4.c.html#1]]]
} 
@enduml
