@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#538]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#540]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#543]]]
getchar(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1376]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1385]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1395]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1402]]]
putchar(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1411]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1420]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1430]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1437]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1443]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1450]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1469]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1482]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1501]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1515]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1536]]]
printf(char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1543]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1555]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1565]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1580]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1591]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1610]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1636]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1663]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1834]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1839]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1846]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1993]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2008]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2018]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2030]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2036]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2042]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#2710]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm.c.html#1]]]
} 
@enduml
