@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#781]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#790]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#800]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#807]]]
putchar(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#816]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#825]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#835]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#842]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#848]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#855]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#874]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#887]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#906]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#920]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#941]]]
printf(char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#948]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#960]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#970]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#985]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#996]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1015]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1041]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1068]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1348]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1350]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1353]]]
OSSL_FUNC_core_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_core_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1636]]]
OSSL_FUNC_core_get_params(OSSL_DISPATCH*) : OSSL_FUNC_core_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1639]]]
OSSL_FUNC_core_thread_start(OSSL_DISPATCH*) : OSSL_FUNC_core_thread_start_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1642]]]
OSSL_FUNC_core_get_libctx(OSSL_DISPATCH*) : OSSL_FUNC_core_get_libctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1646]]]
OSSL_FUNC_core_new_error(OSSL_DISPATCH*) : OSSL_FUNC_core_new_error_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1649]]]
OSSL_FUNC_core_set_error_debug(OSSL_DISPATCH*) : OSSL_FUNC_core_set_error_debug_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1651]]]
OSSL_FUNC_core_vset_error(OSSL_DISPATCH*) : OSSL_FUNC_core_vset_error_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1655]]]
OSSL_FUNC_core_set_error_mark(OSSL_DISPATCH*) : OSSL_FUNC_core_set_error_mark_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1659]]]
OSSL_FUNC_core_clear_last_error_mark(OSSL_DISPATCH*) : OSSL_FUNC_core_clear_last_error_mark_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1661]]]
OSSL_FUNC_core_pop_error_to_mark(OSSL_DISPATCH*) : OSSL_FUNC_core_pop_error_to_mark_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1664]]]
OSSL_FUNC_core_obj_add_sigid(OSSL_DISPATCH*) : OSSL_FUNC_core_obj_add_sigid_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1672]]]
OSSL_FUNC_core_obj_create(OSSL_DISPATCH*) : OSSL_FUNC_core_obj_create_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1675]]]
OSSL_FUNC_CRYPTO_malloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_malloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1681]]]
OSSL_FUNC_CRYPTO_zalloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_zalloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1684]]]
OSSL_FUNC_CRYPTO_free(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1687]]]
OSSL_FUNC_CRYPTO_clear_free(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_clear_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1690]]]
OSSL_FUNC_CRYPTO_realloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_realloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1693]]]
OSSL_FUNC_CRYPTO_clear_realloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_clear_realloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1696]]]
OSSL_FUNC_CRYPTO_secure_malloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_secure_malloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1700]]]
OSSL_FUNC_CRYPTO_secure_zalloc(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_secure_zalloc_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1703]]]
OSSL_FUNC_CRYPTO_secure_free(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_secure_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1706]]]
OSSL_FUNC_CRYPTO_secure_clear_free(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_secure_clear_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1709]]]
OSSL_FUNC_CRYPTO_secure_allocated(OSSL_DISPATCH*) : OSSL_FUNC_CRYPTO_secure_allocated_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1713]]]
OSSL_FUNC_OPENSSL_cleanse(OSSL_DISPATCH*) : OSSL_FUNC_OPENSSL_cleanse_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1716]]]
OSSL_FUNC_BIO_new_file(OSSL_DISPATCH*) : OSSL_FUNC_BIO_new_file_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1718]]]
OSSL_FUNC_BIO_new_membuf(OSSL_DISPATCH*) : OSSL_FUNC_BIO_new_membuf_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1720]]]
OSSL_FUNC_BIO_read_ex(OSSL_DISPATCH*) : OSSL_FUNC_BIO_read_ex_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1721]]]
OSSL_FUNC_BIO_write_ex(OSSL_DISPATCH*) : OSSL_FUNC_BIO_write_ex_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1723]]]
OSSL_FUNC_BIO_gets(OSSL_DISPATCH*) : OSSL_FUNC_BIO_gets_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1725]]]
OSSL_FUNC_BIO_puts(OSSL_DISPATCH*) : OSSL_FUNC_BIO_puts_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1726]]]
OSSL_FUNC_BIO_up_ref(OSSL_DISPATCH*) : OSSL_FUNC_BIO_up_ref_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1727]]]
OSSL_FUNC_BIO_free(OSSL_DISPATCH*) : OSSL_FUNC_BIO_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1728]]]
OSSL_FUNC_BIO_vprintf(OSSL_DISPATCH*) : OSSL_FUNC_BIO_vprintf_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1729]]]
OSSL_FUNC_BIO_vsnprintf(OSSL_DISPATCH*) : OSSL_FUNC_BIO_vsnprintf_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1731]]]
OSSL_FUNC_BIO_ctrl(OSSL_DISPATCH*) : OSSL_FUNC_BIO_ctrl_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1733]]]
OSSL_FUNC_self_test_cb(OSSL_DISPATCH*) : OSSL_FUNC_self_test_cb_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1737]]]
OSSL_FUNC_get_entropy(OSSL_DISPATCH*) : OSSL_FUNC_get_entropy_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1745]]]
OSSL_FUNC_cleanup_entropy(OSSL_DISPATCH*) : OSSL_FUNC_cleanup_entropy_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1748]]]
OSSL_FUNC_get_nonce(OSSL_DISPATCH*) : OSSL_FUNC_get_nonce_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1750]]]
OSSL_FUNC_cleanup_nonce(OSSL_DISPATCH*) : OSSL_FUNC_cleanup_nonce_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1754]]]
OSSL_FUNC_provider_register_child_cb(OSSL_DISPATCH*) : OSSL_FUNC_provider_register_child_cb_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1756]]]
OSSL_FUNC_provider_deregister_child_cb(OSSL_DISPATCH*) : OSSL_FUNC_provider_deregister_child_cb_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1762]]]
OSSL_FUNC_provider_name(OSSL_DISPATCH*) : OSSL_FUNC_provider_name_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1764]]]
OSSL_FUNC_provider_get0_provider_ctx(OSSL_DISPATCH*) : OSSL_FUNC_provider_get0_provider_ctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1766]]]
OSSL_FUNC_provider_get0_dispatch(OSSL_DISPATCH*) : OSSL_FUNC_provider_get0_dispatch_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1768]]]
OSSL_FUNC_provider_up_ref(OSSL_DISPATCH*) : OSSL_FUNC_provider_up_ref_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1770]]]
OSSL_FUNC_provider_free(OSSL_DISPATCH*) : OSSL_FUNC_provider_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1772]]]
OSSL_FUNC_provider_teardown(OSSL_DISPATCH*) : OSSL_FUNC_provider_teardown_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1777]]]
OSSL_FUNC_provider_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_provider_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1779]]]
OSSL_FUNC_provider_get_params(OSSL_DISPATCH*) : OSSL_FUNC_provider_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1782]]]
OSSL_FUNC_provider_query_operation(OSSL_DISPATCH*) : OSSL_FUNC_provider_query_operation_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1785]]]
OSSL_FUNC_provider_unquery_operation(OSSL_DISPATCH*) : OSSL_FUNC_provider_unquery_operation_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1788]]]
OSSL_FUNC_provider_get_reason_strings(OSSL_DISPATCH*) : OSSL_FUNC_provider_get_reason_strings_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1791]]]
OSSL_FUNC_provider_get_capabilities(OSSL_DISPATCH*) : OSSL_FUNC_provider_get_capabilities_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1794]]]
OSSL_FUNC_provider_self_test(OSSL_DISPATCH*) : OSSL_FUNC_provider_self_test_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1797]]]
OSSL_FUNC_digest_newctx(OSSL_DISPATCH*) : OSSL_FUNC_digest_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1799]]]
OSSL_FUNC_digest_init(OSSL_DISPATCH*) : OSSL_FUNC_digest_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1800]]]
OSSL_FUNC_digest_update(OSSL_DISPATCH*) : OSSL_FUNC_digest_update_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1801]]]
OSSL_FUNC_digest_final(OSSL_DISPATCH*) : OSSL_FUNC_digest_final_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1803]]]
OSSL_FUNC_digest_digest(OSSL_DISPATCH*) : OSSL_FUNC_digest_digest_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1806]]]
OSSL_FUNC_digest_freectx(OSSL_DISPATCH*) : OSSL_FUNC_digest_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1810]]]
OSSL_FUNC_digest_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_digest_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1811]]]
OSSL_FUNC_digest_get_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1813]]]
OSSL_FUNC_digest_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1814]]]
OSSL_FUNC_digest_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1816]]]
OSSL_FUNC_digest_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1818]]]
OSSL_FUNC_digest_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1820]]]
OSSL_FUNC_digest_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_digest_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1822]]]
OSSL_FUNC_cipher_newctx(OSSL_DISPATCH*) : OSSL_FUNC_cipher_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1824]]]
OSSL_FUNC_cipher_encrypt_init(OSSL_DISPATCH*) : OSSL_FUNC_cipher_encrypt_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1825]]]
OSSL_FUNC_cipher_decrypt_init(OSSL_DISPATCH*) : OSSL_FUNC_cipher_decrypt_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1831]]]
OSSL_FUNC_cipher_update(OSSL_DISPATCH*) : OSSL_FUNC_cipher_update_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1837]]]
OSSL_FUNC_cipher_final(OSSL_DISPATCH*) : OSSL_FUNC_cipher_final_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1841]]]
OSSL_FUNC_cipher_cipher(OSSL_DISPATCH*) : OSSL_FUNC_cipher_cipher_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1844]]]
OSSL_FUNC_cipher_freectx(OSSL_DISPATCH*) : OSSL_FUNC_cipher_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1848]]]
OSSL_FUNC_cipher_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_cipher_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1849]]]
OSSL_FUNC_cipher_get_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1850]]]
OSSL_FUNC_cipher_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1851]]]
OSSL_FUNC_cipher_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1853]]]
OSSL_FUNC_cipher_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1855]]]
OSSL_FUNC_cipher_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1857]]]
OSSL_FUNC_cipher_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_cipher_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1859]]]
OSSL_FUNC_mac_newctx(OSSL_DISPATCH*) : OSSL_FUNC_mac_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1861]]]
OSSL_FUNC_mac_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_mac_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1862]]]
OSSL_FUNC_mac_freectx(OSSL_DISPATCH*) : OSSL_FUNC_mac_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1863]]]
OSSL_FUNC_mac_init(OSSL_DISPATCH*) : OSSL_FUNC_mac_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1864]]]
OSSL_FUNC_mac_update(OSSL_DISPATCH*) : OSSL_FUNC_mac_update_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1866]]]
OSSL_FUNC_mac_final(OSSL_DISPATCH*) : OSSL_FUNC_mac_final_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1868]]]
OSSL_FUNC_mac_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1871]]]
OSSL_FUNC_mac_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1872]]]
OSSL_FUNC_mac_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1874]]]
OSSL_FUNC_mac_get_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1876]]]
OSSL_FUNC_mac_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1877]]]
OSSL_FUNC_mac_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_mac_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1879]]]
OSSL_FUNC_kdf_newctx(OSSL_DISPATCH*) : OSSL_FUNC_kdf_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1881]]]
OSSL_FUNC_kdf_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_kdf_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1882]]]
OSSL_FUNC_kdf_freectx(OSSL_DISPATCH*) : OSSL_FUNC_kdf_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1883]]]
OSSL_FUNC_kdf_reset(OSSL_DISPATCH*) : OSSL_FUNC_kdf_reset_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1884]]]
OSSL_FUNC_kdf_derive(OSSL_DISPATCH*) : OSSL_FUNC_kdf_derive_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1885]]]
OSSL_FUNC_kdf_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1887]]]
OSSL_FUNC_kdf_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1888]]]
OSSL_FUNC_kdf_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1890]]]
OSSL_FUNC_kdf_get_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1892]]]
OSSL_FUNC_kdf_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1893]]]
OSSL_FUNC_kdf_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kdf_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1895]]]
OSSL_FUNC_rand_newctx(OSSL_DISPATCH*) : OSSL_FUNC_rand_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1897]]]
OSSL_FUNC_rand_freectx(OSSL_DISPATCH*) : OSSL_FUNC_rand_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1900]]]
OSSL_FUNC_rand_instantiate(OSSL_DISPATCH*) : OSSL_FUNC_rand_instantiate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1901]]]
OSSL_FUNC_rand_uninstantiate(OSSL_DISPATCH*) : OSSL_FUNC_rand_uninstantiate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1906]]]
OSSL_FUNC_rand_generate(OSSL_DISPATCH*) : OSSL_FUNC_rand_generate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1907]]]
OSSL_FUNC_rand_reseed(OSSL_DISPATCH*) : OSSL_FUNC_rand_reseed_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1911]]]
OSSL_FUNC_rand_nonce(OSSL_DISPATCH*) : OSSL_FUNC_rand_nonce_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1915]]]
OSSL_FUNC_rand_enable_locking(OSSL_DISPATCH*) : OSSL_FUNC_rand_enable_locking_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1918]]]
OSSL_FUNC_rand_lock(OSSL_DISPATCH*) : OSSL_FUNC_rand_lock_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1919]]]
OSSL_FUNC_rand_unlock(OSSL_DISPATCH*) : OSSL_FUNC_rand_unlock_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1920]]]
OSSL_FUNC_rand_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1921]]]
OSSL_FUNC_rand_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1922]]]
OSSL_FUNC_rand_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1924]]]
OSSL_FUNC_rand_get_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1926]]]
OSSL_FUNC_rand_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1927]]]
OSSL_FUNC_rand_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_rand_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1929]]]
OSSL_FUNC_rand_set_callbacks(OSSL_DISPATCH*) : OSSL_FUNC_rand_set_callbacks_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1931]]]
OSSL_FUNC_rand_verify_zeroization(OSSL_DISPATCH*) : OSSL_FUNC_rand_verify_zeroization_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1936]]]
OSSL_FUNC_rand_get_seed(OSSL_DISPATCH*) : OSSL_FUNC_rand_get_seed_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1938]]]
OSSL_FUNC_rand_clear_seed(OSSL_DISPATCH*) : OSSL_FUNC_rand_clear_seed_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1943]]]
OSSL_FUNC_keymgmt_new(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_new_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1945]]]
OSSL_FUNC_keymgmt_gen_init(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1947]]]
OSSL_FUNC_keymgmt_gen_set_template(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_set_template_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1949]]]
OSSL_FUNC_keymgmt_gen_set_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_set_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1951]]]
OSSL_FUNC_keymgmt_gen_settable_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_settable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1953]]]
OSSL_FUNC_keymgmt_gen(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1956]]]
OSSL_FUNC_keymgmt_gen_cleanup(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gen_cleanup_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1958]]]
OSSL_FUNC_keymgmt_load(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_load_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1962]]]
OSSL_FUNC_keymgmt_free(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_free_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1967]]]
OSSL_FUNC_keymgmt_get_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1972]]]
OSSL_FUNC_keymgmt_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1974]]]
OSSL_FUNC_keymgmt_set_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_set_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1979]]]
OSSL_FUNC_keymgmt_settable_params(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_settable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1981]]]
OSSL_FUNC_keymgmt_query_operation_name(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_query_operation_name_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1986]]]
OSSL_FUNC_keymgmt_has(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_has_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1991]]]
OSSL_FUNC_keymgmt_validate(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_validate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#1995]]]
OSSL_FUNC_keymgmt_match(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_match_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2000]]]
OSSL_FUNC_keymgmt_import(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_import_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2002]]]
OSSL_FUNC_keymgmt_import_types(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_import_types_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2004]]]
OSSL_FUNC_keymgmt_export(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_export_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2006]]]
OSSL_FUNC_keymgmt_export_types(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_export_types_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2009]]]
OSSL_FUNC_keymgmt_dup(OSSL_DISPATCH*) : OSSL_FUNC_keymgmt_dup_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2014]]]
OSSL_FUNC_keyexch_newctx(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2016]]]
OSSL_FUNC_keyexch_init(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2017]]]
OSSL_FUNC_keyexch_derive(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_derive_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2019]]]
OSSL_FUNC_keyexch_set_peer(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_set_peer_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2021]]]
OSSL_FUNC_keyexch_freectx(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2022]]]
OSSL_FUNC_keyexch_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2023]]]
OSSL_FUNC_keyexch_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2024]]]
OSSL_FUNC_keyexch_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2026]]]
OSSL_FUNC_keyexch_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2028]]]
OSSL_FUNC_keyexch_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_keyexch_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2030]]]
OSSL_FUNC_signature_newctx(OSSL_DISPATCH*) : OSSL_FUNC_signature_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2032]]]
OSSL_FUNC_signature_sign_init(OSSL_DISPATCH*) : OSSL_FUNC_signature_sign_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2034]]]
OSSL_FUNC_signature_sign(OSSL_DISPATCH*) : OSSL_FUNC_signature_sign_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2036]]]
OSSL_FUNC_signature_verify_init(OSSL_DISPATCH*) : OSSL_FUNC_signature_verify_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2040]]]
OSSL_FUNC_signature_verify(OSSL_DISPATCH*) : OSSL_FUNC_signature_verify_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2042]]]
OSSL_FUNC_signature_verify_recover_init(OSSL_DISPATCH*) : OSSL_FUNC_signature_verify_recover_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2047]]]
OSSL_FUNC_signature_verify_recover(OSSL_DISPATCH*) : OSSL_FUNC_signature_verify_recover_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2049]]]
OSSL_FUNC_signature_digest_sign_init(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_sign_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2052]]]
OSSL_FUNC_signature_digest_sign_update(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_sign_update_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2055]]]
OSSL_FUNC_signature_digest_sign_final(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_sign_final_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2057]]]
OSSL_FUNC_signature_digest_sign(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_sign_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2060]]]
OSSL_FUNC_signature_digest_verify_init(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_verify_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2063]]]
OSSL_FUNC_signature_digest_verify_update(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_verify_update_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2066]]]
OSSL_FUNC_signature_digest_verify_final(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_verify_final_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2068]]]
OSSL_FUNC_signature_digest_verify(OSSL_DISPATCH*) : OSSL_FUNC_signature_digest_verify_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2070]]]
OSSL_FUNC_signature_freectx(OSSL_DISPATCH*) : OSSL_FUNC_signature_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2073]]]
OSSL_FUNC_signature_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_signature_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2074]]]
OSSL_FUNC_signature_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2075]]]
OSSL_FUNC_signature_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2077]]]
OSSL_FUNC_signature_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2079]]]
OSSL_FUNC_signature_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2081]]]
OSSL_FUNC_signature_get_ctx_md_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_get_ctx_md_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2083]]]
OSSL_FUNC_signature_gettable_ctx_md_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_gettable_ctx_md_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2085]]]
OSSL_FUNC_signature_set_ctx_md_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_set_ctx_md_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2087]]]
OSSL_FUNC_signature_settable_ctx_md_params(OSSL_DISPATCH*) : OSSL_FUNC_signature_settable_ctx_md_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2089]]]
OSSL_FUNC_asym_cipher_newctx(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2091]]]
OSSL_FUNC_asym_cipher_encrypt_init(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_encrypt_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2092]]]
OSSL_FUNC_asym_cipher_encrypt(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_encrypt_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2094]]]
OSSL_FUNC_asym_cipher_decrypt_init(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_decrypt_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2099]]]
OSSL_FUNC_asym_cipher_decrypt(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_decrypt_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2101]]]
OSSL_FUNC_asym_cipher_freectx(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2106]]]
OSSL_FUNC_asym_cipher_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2107]]]
OSSL_FUNC_asym_cipher_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2108]]]
OSSL_FUNC_asym_cipher_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2110]]]
OSSL_FUNC_asym_cipher_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2112]]]
OSSL_FUNC_asym_cipher_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_asym_cipher_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2114]]]
OSSL_FUNC_kem_newctx(OSSL_DISPATCH*) : OSSL_FUNC_kem_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2116]]]
OSSL_FUNC_kem_encapsulate_init(OSSL_DISPATCH*) : OSSL_FUNC_kem_encapsulate_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2117]]]
OSSL_FUNC_kem_auth_encapsulate_init(OSSL_DISPATCH*) : OSSL_FUNC_kem_auth_encapsulate_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2119]]]
OSSL_FUNC_kem_encapsulate(OSSL_DISPATCH*) : OSSL_FUNC_kem_encapsulate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2122]]]
OSSL_FUNC_kem_decapsulate_init(OSSL_DISPATCH*) : OSSL_FUNC_kem_decapsulate_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2126]]]
OSSL_FUNC_kem_auth_decapsulate_init(OSSL_DISPATCH*) : OSSL_FUNC_kem_auth_decapsulate_init_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2128]]]
OSSL_FUNC_kem_decapsulate(OSSL_DISPATCH*) : OSSL_FUNC_kem_decapsulate_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2131]]]
OSSL_FUNC_kem_freectx(OSSL_DISPATCH*) : OSSL_FUNC_kem_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2134]]]
OSSL_FUNC_kem_dupctx(OSSL_DISPATCH*) : OSSL_FUNC_kem_dupctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2135]]]
OSSL_FUNC_kem_get_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kem_get_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2136]]]
OSSL_FUNC_kem_gettable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kem_gettable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2137]]]
OSSL_FUNC_kem_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kem_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2139]]]
OSSL_FUNC_kem_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_kem_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2141]]]
OSSL_FUNC_encoder_newctx(OSSL_DISPATCH*) : OSSL_FUNC_encoder_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2143]]]
OSSL_FUNC_encoder_freectx(OSSL_DISPATCH*) : OSSL_FUNC_encoder_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2144]]]
OSSL_FUNC_encoder_get_params(OSSL_DISPATCH*) : OSSL_FUNC_encoder_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2145]]]
OSSL_FUNC_encoder_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_encoder_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2146]]]
OSSL_FUNC_encoder_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_encoder_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2148]]]
OSSL_FUNC_encoder_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_encoder_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2150]]]
OSSL_FUNC_encoder_does_selection(OSSL_DISPATCH*) : OSSL_FUNC_encoder_does_selection_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2153]]]
OSSL_FUNC_encoder_encode(OSSL_DISPATCH*) : OSSL_FUNC_encoder_encode_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2155]]]
OSSL_FUNC_encoder_import_object(OSSL_DISPATCH*) : OSSL_FUNC_encoder_import_object_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2161]]]
OSSL_FUNC_encoder_free_object(OSSL_DISPATCH*) : OSSL_FUNC_encoder_free_object_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2163]]]
OSSL_FUNC_decoder_newctx(OSSL_DISPATCH*) : OSSL_FUNC_decoder_newctx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2165]]]
OSSL_FUNC_decoder_freectx(OSSL_DISPATCH*) : OSSL_FUNC_decoder_freectx_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2166]]]
OSSL_FUNC_decoder_get_params(OSSL_DISPATCH*) : OSSL_FUNC_decoder_get_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2167]]]
OSSL_FUNC_decoder_gettable_params(OSSL_DISPATCH*) : OSSL_FUNC_decoder_gettable_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2168]]]
OSSL_FUNC_decoder_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_decoder_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2170]]]
OSSL_FUNC_decoder_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_decoder_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2172]]]
OSSL_FUNC_decoder_does_selection(OSSL_DISPATCH*) : OSSL_FUNC_decoder_does_selection_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2175]]]
OSSL_FUNC_decoder_decode(OSSL_DISPATCH*) : OSSL_FUNC_decoder_decode_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2177]]]
OSSL_FUNC_decoder_export_object(OSSL_DISPATCH*) : OSSL_FUNC_decoder_export_object_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2181]]]
OSSL_FUNC_store_open(OSSL_DISPATCH*) : OSSL_FUNC_store_open_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2183]]]
OSSL_FUNC_store_attach(OSSL_DISPATCH*) : OSSL_FUNC_store_attach_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2184]]]
OSSL_FUNC_store_settable_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_store_settable_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2185]]]
OSSL_FUNC_store_set_ctx_params(OSSL_DISPATCH*) : OSSL_FUNC_store_set_ctx_params_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2187]]]
OSSL_FUNC_store_load(OSSL_DISPATCH*) : OSSL_FUNC_store_load_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2189]]]
OSSL_FUNC_store_eof(OSSL_DISPATCH*) : OSSL_FUNC_store_eof_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2193]]]
OSSL_FUNC_store_close(OSSL_DISPATCH*) : OSSL_FUNC_store_close_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2194]]]
OSSL_FUNC_store_export_object(OSSL_DISPATCH*) : OSSL_FUNC_store_export_object_fn [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2195]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2329]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2334]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2341]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2488]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2503]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2513]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2525]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2531]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_aes_gcm_siv_hw.c.html#2537]]]
} 
@enduml
