@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#490]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#492]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#495]]]
getchar(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1328]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1337]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1347]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1354]]]
putchar(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1363]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1372]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1382]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1389]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1395]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1402]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1421]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1434]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1453]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1467]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1488]]]
printf(char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1495]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1507]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1517]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1532]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1543]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1562]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1588]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1615]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1786]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1791]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1798]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1945]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1960]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1970]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1982]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1988]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#1994]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_cast5_hw.c.html#2662]]]
} 
@enduml
