@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#469]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#471]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/ciphers/cipher_sm4_ccm.c.html#474]]]
} 
@enduml
