@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#582]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#589]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/sm3/sm3.c.html#630]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/sm3/sm3.c.html#638]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/crypto/sm3/sm3.c.html#645]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#658]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#665]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#672]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#680]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#690]]]
strcat(char*;char*) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#697]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/sm3/sm3.c.html#704]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#878]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#883]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sm3/sm3.c.html#890]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1052]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1067]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1077]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1089]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1095]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/sm3/sm3.c.html#1101]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/sm3/sm3.c.html#1769]]]
} 
@enduml
