@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/conf/conf_api.c.html#501]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/conf/conf_api.c.html#506]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/conf/conf_api.c.html#513]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/conf/conf_api.c.html#675]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/conf/conf_api.c.html#690]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/conf/conf_api.c.html#700]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/conf/conf_api.c.html#712]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/conf/conf_api.c.html#718]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/conf/conf_api.c.html#724]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/conf/conf_api.c.html#1392]]]
} 
@enduml
