@startuml
!pragma layout smetana
class dummy {
rotl(uint32_t;uint8_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#541]]]
load_u32_be(uint8_t*;uint32_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#546]]]
store_u32_be(uint32_t;uint8_t*) :  void  [[[./../../.././qc/crypto/sm4/sm4.c.html#554]]]
SM4_T_non_lin_sub(uint32_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#562]]]
SM4_T_slow(uint32_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#574]]]
SM4_T(uint32_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#584]]]
SM4_key_sub(uint32_t) : uint32_t [[[./../../.././qc/crypto/sm4/sm4.c.html#592]]]
ossl_sm4_set_key(uint8_t*;SM4_KEY*) :  int  [[[./../../.././qc/crypto/sm4/sm4.c.html#599]]]
ossl_sm4_encrypt(uint8_t*;uint8_t*;SM4_KEY*) :  void  [[[./../../.././qc/crypto/sm4/sm4.c.html#643]]]
ossl_sm4_decrypt(uint8_t*;uint8_t*;SM4_KEY*) :  void  [[[./../../.././qc/crypto/sm4/sm4.c.html#669]]]
} 
@enduml
