@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#298]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#305]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#346]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#354]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#361]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#374]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#381]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#388]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#396]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#406]]]
strcat(char*;char*) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#413]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#420]]]
getchar(void) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1135]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1144]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1154]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1161]]]
putchar(int) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1170]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1179]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1189]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1196]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1202]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1209]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1228]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1241]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1260]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1274]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1295]]]
printf(char*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1302]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1314]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1324]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1339]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1350]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1369]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1395]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#1422]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2027]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2032]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2039]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2138]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2153]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2163]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2175]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2181]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2187]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/cmp/cmp_http.c.html#2840]]]
} 
@enduml
