@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_client.c.html#175]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_client.c.html#180]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmp/cmp_client.c.html#187]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#487]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#502]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#512]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#524]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#530]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmp/cmp_client.c.html#536]]]
} 
@enduml
