@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/property/property_query.c.html#480]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/property/property_query.c.html#485]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/property/property_query.c.html#492]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/property/property_query.c.html#654]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/property/property_query.c.html#669]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/property/property_query.c.html#679]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/property/property_query.c.html#691]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/property/property_query.c.html#697]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/property/property_query.c.html#703]]]
} 
@enduml
