@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#171]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#176]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#183]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#483]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#498]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#508]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#520]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#526]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#532]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1200]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
memcpy(void*;void*;size_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
memmove(void*;void*;size_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
memset(void*;int;size_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
strcpy(char*;char*) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
stpcpy(char*;char*) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
strncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
strcat(char*;char*) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
strncat(char*;char*;size_t) :  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_msb(unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_msb_32(uint32_t) : uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_msb_64(uint64_t) : uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_msb_s(size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_lt(unsignedint;unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_lt_s(size_t;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_lt_8(unsignedint;unsignedint) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_lt_64(uint64_t;uint64_t) : uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_ge(unsignedint;unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_ge_s(size_t;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_ge_8(unsignedint;unsignedint) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_ge_8_s(size_t;size_t) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_is_zero(unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_is_zero_s(size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_is_zero_8(unsignedint) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_is_zero_32(uint32_t) : uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_is_zero_64(uint64_t) : uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq(unsignedint;unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq_s(size_t;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq_8(unsignedint;unsignedint) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq_8_s(size_t;size_t) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq_int(int;int) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_eq_int_8(int;int) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
value_barrier(unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
value_barrier_32(uint32_t) : uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
value_barrier_64(uint64_t) : uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
value_barrier_s(size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select(unsignedint;unsignedint;unsignedint) :  unsigned  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_s(size_t;size_t;size_t) : size_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_8(unsignedchar;unsignedchar;unsignedchar) :  unsigned  char  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_int(unsignedint;int;int) :  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_int_s(size_t;int;int) :  int  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_32(uint32_t;uint32_t;uint32_t) : uint32_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_select_64(uint64_t;uint64_t;uint64_t) : uint64_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_cond_swap_32(uint32_t;uint32_t*;uint32_t*) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_cond_swap_64(uint64_t;uint64_t*;uint64_t*) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_cond_swap_buff(unsignedchar;unsignedchar*;unsignedchar*;size_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
constant_time_lookup(void*;void*;size_t;size_t;size_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
c448_succeed_if(c448_bool_t) : c448_error_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
widemul(uint64_t;uint64_t) : uint128_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
mask_to_bool(mask_t) : c448_bool_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
bool_to_mask(c448_bool_t) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_copy(gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_add_RAW(gf;gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_sub_RAW(gf;gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_bias(gf;int) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_weak_reduce(gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_sqrn(gf_s*;gf;int) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_sub_nr(gf;gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_subx_nr(gf;gf;gf;int) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_mulw(gf;gf;int32_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_cond_sel(gf;gf;gf;mask_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_cond_neg(gf;mask_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_cond_swap(gf;gf_s*;mask_t) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_serialize(uint8_t;gf;int) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_hibit(gf) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_lobit(gf) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_deserialize(gf;uint8_t;int;uint8_t) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_strong_reduce(gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_sub(gf;gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_add(gf;gf;gf) :  void  [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_eq(gf;gf) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
gf_isr(gf;gf) : mask_t [[[./../../../.././qc/crypto/ec/curve448/f_generic.c.html#1]]]
} 
@enduml
