@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#333]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#340]]]
memcpy(void*;void*;size_t) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#381]]]
memmove(void*;void*;size_t) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#389]]]
memset(void*;int;size_t) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#396]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#409]]]
strcpy(char*;char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#416]]]
stpcpy(char*;char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#423]]]
strncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#431]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#441]]]
strcat(char*;char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#448]]]
strncat(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#455]]]
getchar(void) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1311]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1320]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1330]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1337]]]
putchar(int) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1346]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1355]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1365]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1372]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1378]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1385]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1404]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1417]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1436]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1450]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1471]]]
printf(char*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1478]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1490]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1500]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1515]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1526]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1545]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1571]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1598]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1751]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1753]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1756]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2066]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2071]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2078]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2225]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2240]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2250]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2262]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2268]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2274]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#2942]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/common/der/der_dsa_sig.c.html#1]]]
} 
@enduml
