@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#458]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#463]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#470]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#632]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#647]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#657]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#669]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#675]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/crypto/thread/arch/thread_none.c.html#681]]]
} 
@enduml
