@startuml
 <|-- dummy.__locale_struct
 <|-- dummy.
 <|-- dummy.timespec
 <|-- dummy.stat
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy._IO_marker
 <|-- dummy._IO_FILE
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.timeval
 <|-- dummy.
 <|-- dummy.__pthread_rwlock_arch_t
 <|-- dummy.__pthread_internal_list
 <|-- dummy.__pthread_mutex_s
 <|-- dummy.__pthread_cond_s
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.pthread_attr_t
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.random_data
 <|-- dummy.drand48_data
 <|-- dummy.tm
 <|-- dummy.itimerspec
 <|-- dummy.
 <|-- dummy.crypto_ex_data_st
 <|-- dummy.crypto_threadid_st
 <|-- dummy.sched_param
 <|-- dummy.
 <|-- dummy._pthread_cleanup_buffer
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.__pthread_cleanup_frame
 <|-- dummy.BIO_sock_info_u
 <|-- dummy.asn1_string_st
 <|-- dummy.ASN1_ENCODING_st
 <|-- dummy.asn1_string_table_st
 <|-- dummy.asn1_type_st
 <|-- dummy.
 <|-- dummy.BIT_STRING_BITNAME_st
 <|-- dummy.lhash_st_OPENSSL_STRING
 <|-- dummy.lh_OPENSSL_STRING_dummy
 <|-- dummy.lhash_st_OPENSSL_CSTRING
 <|-- dummy.lh_OPENSSL_CSTRING_dummy
 <|-- dummy.err_state_st
 <|-- dummy.ERR_string_data_st
 <|-- dummy.lhash_st_ERR_STRING_DATA
 <|-- dummy.lh_ERR_STRING_DATA_dummy
 <|-- dummy.
 <|-- dummy.ossl_dispatch_st
 <|-- dummy.ossl_item_st
 <|-- dummy.ossl_algorithm_st
 <|-- dummy.ossl_param_st
 <|-- dummy.obj_name_st
 <|-- dummy.
 <|-- dummy.evp_cipher_info_st
 <|-- dummy.buf_mem_st
 <|-- dummy.
 <|-- dummy.rsa_pss_params_st
 <|-- dummy.rsa_oaep_params_st
 <|-- dummy.SHAstate_st
 <|-- dummy.SHA256state_st
 <|-- dummy.SHA512state_st
 <|-- dummy.
 <|-- dummy.X509_algor_st
 <|-- dummy.X509_val_st
 <|-- dummy.x509_trust_st
 <|-- dummy.private_key_st
 <|-- dummy.X509_info_st
 <|-- dummy.Netscape_spkac_st
 <|-- dummy.Netscape_spki_st
 <|-- dummy.Netscape_certificate_sequence
 <|-- dummy.PBEPARAM_st
 <|-- dummy.PBE2PARAM_st
 <|-- dummy.PBKDF2PARAM_st
 <|-- dummy.SCRYPT_PARAMS_st
 <|-- dummy.PKCS7_CTX_st
 <|-- dummy.pkcs7_issuer_and_serial_st
 <|-- dummy.pkcs7_signer_info_st
 <|-- dummy.pkcs7_recip_info_st
 <|-- dummy.pkcs7_signed_st
 <|-- dummy.pkcs7_enc_content_st
 <|-- dummy.pkcs7_enveloped_st
 <|-- dummy.pkcs7_signedandenveloped_st
 <|-- dummy.pkcs7_digest_st
 <|-- dummy.pkcs7_encrypted_st
 <|-- dummy.pkcs7_st
 <|-- dummy.
 <|-- dummy.rand_meth_st
 <|-- dummy.ENGINE_CMD_DEFN_st
 <|-- dummy.st_dynamic_MEM_fns
 <|-- dummy.st_dynamic_fns
 <|-- dummy.lhash_st_MEM
 <|-- dummy.lh_MEM_dummy
 <|-- dummy.ex_callback_st
 <|-- dummy.ex_callbacks_st
 <|-- dummy.ossl_ex_data_global_st
 <|-- dummy.ossl_lib_ctx_method
 <|-- dummy.pem_pass_data
 <|-- dummy.embedded_st
 <|-- dummy.file_handler_st
 <|-- dummy.ossl_store_loader_ctx_st
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
class dummy. {
+  bcopy(void*;void*;size_t)
+  bzero(void*;size_t)
+  memcpy(void*;void*;size_t)
+  memmove(void*;void*;size_t)
+  memset(void*;int;size_t)
+  explicit_bzero(void*;size_t)
+  strcpy(char*;char*)
+  strncpy(char*;char*;size_t)
+  stpncpy(char*;char*;size_t)
+  strcat(char*;char*)
+  strncat(char*;char*;size_t)
+  stat(char*;structstat*)
+  lstat(char*;structstat*)
+  fstat(int;structstat*)
+  fstatat(int;char*;structstat*;int)
+  mknod(char*;__mode_t;__dev_t)
+  mknodat(int;char*;__mode_t;__dev_t)
+  __bswap_32(unsignedint)
+  __bswap_64(__uint64_t)
+  __uint16_identity(__uint16_t)
+  __uint32_identity(__uint32_t)
+  __uint64_identity(__uint64_t)
+  tolower(int)
+  toupper(int)
+  strtoimax(char*;char*;int)
+  strtoumax(char*;char*;int)
+  wcstoimax(__gwchar_t*;__gwchar_t*;int)
+  wcstoumax(__gwchar_t*;__gwchar_t*;int)
+  getchar(void)
+  fgetc_unlocked(FILE*)
+  getc_unlocked(FILE*)
+  getchar_unlocked(void)
+  putchar(int)
+  fputc_unlocked(int;FILE*)
+  putc_unlocked(int;FILE*)
+  putchar_unlocked(int)
+  feof_unlocked(FILE*)
+  ferror_unlocked(FILE*)
+  sprintf(char*;char*)
+  vsprintf(char*;char*;__gnuc_va_list)
+  snprintf(char*;size_t;char*)
+  vsnprintf(char*;size_t;char*;__gnuc_va_list)
+  fprintf(FILE*;char*)
+  printf(char*)
+  vprintf(char*;__gnuc_va_list)
+  vfprintf(FILE*;char*;__gnuc_va_list)
+  dprintf(int;char*)
+  vdprintf(int;char*;__gnuc_va_list)
+  fgets(char*;int;FILE*)
+  fread(void*;size_t;size_t;FILE*)
+  fread_unlocked(void*;size_t;size_t;FILE*)
+  atoi(char*)
+  atol(char*)
+  atoll(char*)
+  gnu_dev_major(__dev_t)
+  gnu_dev_minor(__dev_t)
+  gnu_dev_makedev(unsignedint;unsignedint)
+  bsearch(void*;void*;size_t;size_t;__compar_fn_t)
+  atof(char*)
+  realpath(char*;char*)
+  ptsname_r(int;char*;size_t)
+  wctomb(char*;wchar_t)
+  mbstowcs(wchar_t*;char*;size_t)
+  wcstombs(char*;wchar_t*;size_t)
+  ossl_check_OPENSSL_STRING_type(char*)
+  ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc)
+  ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc)
+  ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc)
+  ossl_check_OPENSSL_CSTRING_type(char*)
+  ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc)
+  ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc)
+  ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc)
+  ossl_check_OPENSSL_BLOCK_type(void*)
+  ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*)
+  ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*)
+  ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc)
+  ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc)
+  ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc)
+  ossl_check_void_type(void*)
+  ossl_check_const_void_sk_type(structstack_st_void*)
+  ossl_check_void_sk_type(structstack_st_void*)
+  ossl_check_void_compfunc_type(sk_void_compfunc)
+  ossl_check_void_copyfunc_type(sk_void_copyfunc)
+  ossl_check_void_freefunc_type(sk_void_freefunc)
+  pthread_equal(pthread_t;pthread_t)
+  ossl_check_BIO_type(BIO*)
+  ossl_check_const_BIO_sk_type(structstack_st_BIO*)
+  ossl_check_BIO_sk_type(structstack_st_BIO*)
+  ossl_check_BIO_compfunc_type(sk_BIO_compfunc)
+  ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc)
+  ossl_check_BIO_freefunc_type(sk_BIO_freefunc)
+  ossl_check_X509_ALGOR_type(X509_ALGOR*)
+  ossl_check_const_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*)
+  ossl_check_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*)
+  ossl_check_X509_ALGOR_compfunc_type(sk_X509_ALGOR_compfunc)
+  ossl_check_X509_ALGOR_copyfunc_type(sk_X509_ALGOR_copyfunc)
+  ossl_check_X509_ALGOR_freefunc_type(sk_X509_ALGOR_freefunc)
+  ossl_check_ASN1_STRING_TABLE_type(ASN1_STRING_TABLE*)
+  ossl_check_const_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*)
+  ossl_check_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*)
+  ossl_check_ASN1_STRING_TABLE_compfunc_type(sk_ASN1_STRING_TABLE_compfunc)
+  ossl_check_ASN1_STRING_TABLE_copyfunc_type(sk_ASN1_STRING_TABLE_copyfunc)
+  ossl_check_ASN1_STRING_TABLE_freefunc_type(sk_ASN1_STRING_TABLE_freefunc)
+  ossl_check_ASN1_TYPE_type(ASN1_TYPE*)
+  ossl_check_const_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*)
+  ossl_check_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*)
+  ossl_check_ASN1_TYPE_compfunc_type(sk_ASN1_TYPE_compfunc)
+  ossl_check_ASN1_TYPE_copyfunc_type(sk_ASN1_TYPE_copyfunc)
+  ossl_check_ASN1_TYPE_freefunc_type(sk_ASN1_TYPE_freefunc)
+  ossl_check_ASN1_OBJECT_type(ASN1_OBJECT*)
+  ossl_check_const_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*)
+  ossl_check_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*)
+  ossl_check_ASN1_OBJECT_compfunc_type(sk_ASN1_OBJECT_compfunc)
+  ossl_check_ASN1_OBJECT_copyfunc_type(sk_ASN1_OBJECT_copyfunc)
+  ossl_check_ASN1_OBJECT_freefunc_type(sk_ASN1_OBJECT_freefunc)
+  ossl_check_ASN1_INTEGER_type(ASN1_INTEGER*)
+  ossl_check_const_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*)
+  ossl_check_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*)
+  ossl_check_ASN1_INTEGER_compfunc_type(sk_ASN1_INTEGER_compfunc)
+  ossl_check_ASN1_INTEGER_copyfunc_type(sk_ASN1_INTEGER_copyfunc)
+  ossl_check_ASN1_INTEGER_freefunc_type(sk_ASN1_INTEGER_freefunc)
+  ossl_check_ASN1_UTF8STRING_type(ASN1_UTF8STRING*)
+  ossl_check_const_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*)
+  ossl_check_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*)
+  ossl_check_ASN1_UTF8STRING_compfunc_type(sk_ASN1_UTF8STRING_compfunc)
+  ossl_check_ASN1_UTF8STRING_copyfunc_type(sk_ASN1_UTF8STRING_copyfunc)
+  ossl_check_ASN1_UTF8STRING_freefunc_type(sk_ASN1_UTF8STRING_freefunc)
+  ossl_check_ASN1_GENERALSTRING_type(ASN1_GENERALSTRING*)
+  ossl_check_const_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*)
+  ossl_check_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*)
+  ossl_check_ASN1_GENERALSTRING_compfunc_type(sk_ASN1_GENERALSTRING_compfunc)
+  ossl_check_ASN1_GENERALSTRING_copyfunc_type(sk_ASN1_GENERALSTRING_copyfunc)
+  ossl_check_ASN1_GENERALSTRING_freefunc_type(sk_ASN1_GENERALSTRING_freefunc)
+  ossl_check_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*)
+  ossl_check_const_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*)
+  ossl_check_const_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_lh_compfunc_type(lh_OPENSSL_STRING_compfunc)
+  ossl_check_OPENSSL_STRING_lh_hashfunc_type(lh_OPENSSL_STRING_hashfunc)
+  ossl_check_OPENSSL_STRING_lh_doallfunc_type(lh_OPENSSL_STRING_doallfunc)
+  ossl_check_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*)
+  ossl_check_const_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*)
+  ossl_check_const_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_lh_compfunc_type(lh_OPENSSL_CSTRING_compfunc)
+  ossl_check_OPENSSL_CSTRING_lh_hashfunc_type(lh_OPENSSL_CSTRING_hashfunc)
+  ossl_check_OPENSSL_CSTRING_lh_doallfunc_type(lh_OPENSSL_CSTRING_doallfunc)
+  ERR_GET_LIB(unsignedlong)
+  ERR_GET_FUNC(unsignedlong)
+  ERR_GET_RFLAGS(unsignedlong)
+  ERR_GET_REASON(unsignedlong)
+  ERR_FATAL_ERROR(unsignedlong)
+  ERR_COMMON_ERROR(unsignedlong)
+  ossl_check_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*)
+  ossl_check_const_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*)
+  ossl_check_const_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*)
+  ossl_check_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*)
+  ossl_check_ERR_STRING_DATA_lh_compfunc_type(lh_ERR_STRING_DATA_compfunc)
+  ossl_check_ERR_STRING_DATA_lh_hashfunc_type(lh_ERR_STRING_DATA_hashfunc)
+  ossl_check_ERR_STRING_DATA_lh_doallfunc_type(lh_ERR_STRING_DATA_doallfunc)
+  ossl_check_X509_NAME_type(X509_NAME*)
+  ossl_check_const_X509_NAME_sk_type(structstack_st_X509_NAME*)
+  ossl_check_X509_NAME_sk_type(structstack_st_X509_NAME*)
+  ossl_check_X509_NAME_compfunc_type(sk_X509_NAME_compfunc)
+  ossl_check_X509_NAME_copyfunc_type(sk_X509_NAME_copyfunc)
+  ossl_check_X509_NAME_freefunc_type(sk_X509_NAME_freefunc)
+  ossl_check_X509_type(X509*)
+  ossl_check_const_X509_sk_type(structstack_st_X509*)
+  ossl_check_X509_sk_type(structstack_st_X509*)
+  ossl_check_X509_compfunc_type(sk_X509_compfunc)
+  ossl_check_X509_copyfunc_type(sk_X509_copyfunc)
+  ossl_check_X509_freefunc_type(sk_X509_freefunc)
+  ossl_check_X509_REVOKED_type(X509_REVOKED*)
+  ossl_check_const_X509_REVOKED_sk_type(structstack_st_X509_REVOKED*)
+  ossl_check_X509_REVOKED_sk_type(structstack_st_X509_REVOKED*)
+  ossl_check_X509_REVOKED_compfunc_type(sk_X509_REVOKED_compfunc)
+  ossl_check_X509_REVOKED_copyfunc_type(sk_X509_REVOKED_copyfunc)
+  ossl_check_X509_REVOKED_freefunc_type(sk_X509_REVOKED_freefunc)
+  ossl_check_X509_CRL_type(X509_CRL*)
+  ossl_check_const_X509_CRL_sk_type(structstack_st_X509_CRL*)
+  ossl_check_X509_CRL_sk_type(structstack_st_X509_CRL*)
+  ossl_check_X509_CRL_compfunc_type(sk_X509_CRL_compfunc)
+  ossl_check_X509_CRL_copyfunc_type(sk_X509_CRL_copyfunc)
+  ossl_check_X509_CRL_freefunc_type(sk_X509_CRL_freefunc)
+  ossl_check_X509_NAME_ENTRY_type(X509_NAME_ENTRY*)
+  ossl_check_const_X509_NAME_ENTRY_sk_type(structstack_st_X509_NAME_ENTRY*)
+  ossl_check_X509_NAME_ENTRY_sk_type(structstack_st_X509_NAME_ENTRY*)
+  ossl_check_X509_NAME_ENTRY_compfunc_type(sk_X509_NAME_ENTRY_compfunc)
+  ossl_check_X509_NAME_ENTRY_copyfunc_type(sk_X509_NAME_ENTRY_copyfunc)
+  ossl_check_X509_NAME_ENTRY_freefunc_type(sk_X509_NAME_ENTRY_freefunc)
+  ossl_check_X509_EXTENSION_type(X509_EXTENSION*)
+  ossl_check_const_X509_EXTENSION_sk_type(structstack_st_X509_EXTENSION*)
+  ossl_check_X509_EXTENSION_sk_type(structstack_st_X509_EXTENSION*)
+  ossl_check_X509_EXTENSION_compfunc_type(sk_X509_EXTENSION_compfunc)
+  ossl_check_X509_EXTENSION_copyfunc_type(sk_X509_EXTENSION_copyfunc)
+  ossl_check_X509_EXTENSION_freefunc_type(sk_X509_EXTENSION_freefunc)
+  ossl_check_X509_ATTRIBUTE_type(X509_ATTRIBUTE*)
+  ossl_check_const_X509_ATTRIBUTE_sk_type(structstack_st_X509_ATTRIBUTE*)
+  ossl_check_X509_ATTRIBUTE_sk_type(structstack_st_X509_ATTRIBUTE*)
+  ossl_check_X509_ATTRIBUTE_compfunc_type(sk_X509_ATTRIBUTE_compfunc)
+  ossl_check_X509_ATTRIBUTE_copyfunc_type(sk_X509_ATTRIBUTE_copyfunc)
+  ossl_check_X509_ATTRIBUTE_freefunc_type(sk_X509_ATTRIBUTE_freefunc)
+  ossl_check_X509_TRUST_type(X509_TRUST*)
+  ossl_check_const_X509_TRUST_sk_type(structstack_st_X509_TRUST*)
+  ossl_check_X509_TRUST_sk_type(structstack_st_X509_TRUST*)
+  ossl_check_X509_TRUST_compfunc_type(sk_X509_TRUST_compfunc)
+  ossl_check_X509_TRUST_copyfunc_type(sk_X509_TRUST_copyfunc)
+  ossl_check_X509_TRUST_freefunc_type(sk_X509_TRUST_freefunc)
+  ossl_check_X509_INFO_type(X509_INFO*)
+  ossl_check_const_X509_INFO_sk_type(structstack_st_X509_INFO*)
+  ossl_check_X509_INFO_sk_type(structstack_st_X509_INFO*)
+  ossl_check_X509_INFO_compfunc_type(sk_X509_INFO_compfunc)
+  ossl_check_X509_INFO_copyfunc_type(sk_X509_INFO_copyfunc)
+  ossl_check_X509_INFO_freefunc_type(sk_X509_INFO_freefunc)
+  ossl_check_X509_LOOKUP_type(X509_LOOKUP*)
+  ossl_check_const_X509_LOOKUP_sk_type(structstack_st_X509_LOOKUP*)
+  ossl_check_X509_LOOKUP_sk_type(structstack_st_X509_LOOKUP*)
+  ossl_check_X509_LOOKUP_compfunc_type(sk_X509_LOOKUP_compfunc)
+  ossl_check_X509_LOOKUP_copyfunc_type(sk_X509_LOOKUP_copyfunc)
+  ossl_check_X509_LOOKUP_freefunc_type(sk_X509_LOOKUP_freefunc)
+  ossl_check_X509_OBJECT_type(X509_OBJECT*)
+  ossl_check_const_X509_OBJECT_sk_type(structstack_st_X509_OBJECT*)
+  ossl_check_X509_OBJECT_sk_type(structstack_st_X509_OBJECT*)
+  ossl_check_X509_OBJECT_compfunc_type(sk_X509_OBJECT_compfunc)
+  ossl_check_X509_OBJECT_copyfunc_type(sk_X509_OBJECT_copyfunc)
+  ossl_check_X509_OBJECT_freefunc_type(sk_X509_OBJECT_freefunc)
+  ossl_check_X509_VERIFY_PARAM_type(X509_VERIFY_PARAM*)
+  ossl_check_const_X509_VERIFY_PARAM_sk_type(structstack_st_X509_VERIFY_PARAM*)
+  ossl_check_X509_VERIFY_PARAM_sk_type(structstack_st_X509_VERIFY_PARAM*)
+  ossl_check_X509_VERIFY_PARAM_compfunc_type(sk_X509_VERIFY_PARAM_compfunc)
+  ossl_check_X509_VERIFY_PARAM_copyfunc_type(sk_X509_VERIFY_PARAM_copyfunc)
+  ossl_check_X509_VERIFY_PARAM_freefunc_type(sk_X509_VERIFY_PARAM_freefunc)
+  ossl_check_PKCS7_SIGNER_INFO_type(PKCS7_SIGNER_INFO*)
+  ossl_check_const_PKCS7_SIGNER_INFO_sk_type(structstack_st_PKCS7_SIGNER_INFO*)
+  ossl_check_PKCS7_SIGNER_INFO_sk_type(structstack_st_PKCS7_SIGNER_INFO*)
+  ossl_check_PKCS7_SIGNER_INFO_compfunc_type(sk_PKCS7_SIGNER_INFO_compfunc)
+  ossl_check_PKCS7_SIGNER_INFO_copyfunc_type(sk_PKCS7_SIGNER_INFO_copyfunc)
+  ossl_check_PKCS7_SIGNER_INFO_freefunc_type(sk_PKCS7_SIGNER_INFO_freefunc)
+  ossl_check_PKCS7_RECIP_INFO_type(PKCS7_RECIP_INFO*)
+  ossl_check_const_PKCS7_RECIP_INFO_sk_type(structstack_st_PKCS7_RECIP_INFO*)
+  ossl_check_PKCS7_RECIP_INFO_sk_type(structstack_st_PKCS7_RECIP_INFO*)
+  ossl_check_PKCS7_RECIP_INFO_compfunc_type(sk_PKCS7_RECIP_INFO_compfunc)
+  ossl_check_PKCS7_RECIP_INFO_copyfunc_type(sk_PKCS7_RECIP_INFO_copyfunc)
+  ossl_check_PKCS7_RECIP_INFO_freefunc_type(sk_PKCS7_RECIP_INFO_freefunc)
+  ossl_check_PKCS7_type(PKCS7*)
+  ossl_check_const_PKCS7_sk_type(structstack_st_PKCS7*)
+  ossl_check_PKCS7_sk_type(structstack_st_PKCS7*)
+  ossl_check_PKCS7_compfunc_type(sk_PKCS7_compfunc)
+  ossl_check_PKCS7_copyfunc_type(sk_PKCS7_copyfunc)
+  ossl_check_PKCS7_freefunc_type(sk_PKCS7_freefunc)
+  ossl_check_PKCS12_SAFEBAG_type(PKCS12_SAFEBAG*)
+  ossl_check_const_PKCS12_SAFEBAG_sk_type(structstack_st_PKCS12_SAFEBAG*)
+  ossl_check_PKCS12_SAFEBAG_sk_type(structstack_st_PKCS12_SAFEBAG*)
+  ossl_check_PKCS12_SAFEBAG_compfunc_type(sk_PKCS12_SAFEBAG_compfunc)
+  ossl_check_PKCS12_SAFEBAG_copyfunc_type(sk_PKCS12_SAFEBAG_copyfunc)
+  ossl_check_PKCS12_SAFEBAG_freefunc_type(sk_PKCS12_SAFEBAG_freefunc)
+  ossl_check_UI_STRING_type(UI_STRING*)
+  ossl_check_const_UI_STRING_sk_type(structstack_st_UI_STRING*)
+  ossl_check_UI_STRING_sk_type(structstack_st_UI_STRING*)
+  ossl_check_UI_STRING_compfunc_type(sk_UI_STRING_compfunc)
+  ossl_check_UI_STRING_copyfunc_type(sk_UI_STRING_copyfunc)
+  ossl_check_UI_STRING_freefunc_type(sk_UI_STRING_freefunc)
+  sk_EX_CALLBACK_num(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_value(structstack_st_EX_CALLBACK*;int)
+  sk_EX_CALLBACK_new(sk_EX_CALLBACK_compfunc)
+  sk_EX_CALLBACK_new_null(void)
+  sk_EX_CALLBACK_new_reserve(sk_EX_CALLBACK_compfunc;int)
+  sk_EX_CALLBACK_reserve(structstack_st_EX_CALLBACK*;int)
+  sk_EX_CALLBACK_free(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_zero(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_delete(structstack_st_EX_CALLBACK*;int)
+  sk_EX_CALLBACK_delete_ptr(structstack_st_EX_CALLBACK*;EX_CALLBACK*)
+  sk_EX_CALLBACK_push(structstack_st_EX_CALLBACK*;EX_CALLBACK*)
+  sk_EX_CALLBACK_unshift(structstack_st_EX_CALLBACK*;EX_CALLBACK*)
+  sk_EX_CALLBACK_pop(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_shift(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_pop_free(structstack_st_EX_CALLBACK*;sk_EX_CALLBACK_freefunc)
+  sk_EX_CALLBACK_insert(structstack_st_EX_CALLBACK*;EX_CALLBACK*;int)
+  sk_EX_CALLBACK_set(structstack_st_EX_CALLBACK*;int;EX_CALLBACK*)
+  sk_EX_CALLBACK_find(structstack_st_EX_CALLBACK*;EX_CALLBACK*)
+  sk_EX_CALLBACK_find_ex(structstack_st_EX_CALLBACK*;EX_CALLBACK*)
+  sk_EX_CALLBACK_sort(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_is_sorted(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_dup(structstack_st_EX_CALLBACK*)
+  sk_EX_CALLBACK_deep_copy(structstack_st_EX_CALLBACK*;sk_EX_CALLBACK_copyfunc;sk_EX_CALLBACK_freefunc)
+  sk_EX_CALLBACK_set_cmp_func(structstack_st_EX_CALLBACK*;sk_EX_CALLBACK_compfunc)
+  lh_MEM_new(unsignedlong;int)
+  lh_MEM_free(structlhash_st_MEM*)
+  lh_MEM_flush(structlhash_st_MEM*)
+  lh_MEM_insert(structlhash_st_MEM*;MEM*)
+  lh_MEM_delete(structlhash_st_MEM*;MEM*)
+  lh_MEM_retrieve(structlhash_st_MEM*;MEM*)
+  lh_MEM_error(structlhash_st_MEM*)
+  lh_MEM_num_items(structlhash_st_MEM*)
+  lh_MEM_node_stats_bio(structlhash_st_MEM*;BIO*)
+  lh_MEM_node_usage_stats_bio(structlhash_st_MEM*;BIO*)
+  lh_MEM_stats_bio(structlhash_st_MEM*;BIO*)
+  lh_MEM_get_down_load(structlhash_st_MEM*)
+  lh_MEM_set_down_load(structlhash_st_MEM*;unsignedlong)
+  lh_MEM_doall(structlhash_st_MEM*;void)
+  read(int;void*;size_t)
+  readlink(char*;char*;size_t)
+  readlinkat(int;char*;char*;size_t)
+  getcwd(char*;size_t)
+  getwd(char*)
+  confstr(int;char*;size_t)
+  getgroups(int;__gid_t)
+  ttyname_r(int;char*;size_t)
+  getlogin_r(char*;size_t)
+  gethostname(char*;size_t)
+  getdomainname(char*;size_t)
+  ossl_sleep(unsignedlong)
+  ossl_ends_with_dirsep(char*)
+  ossl_is_absolute_path(char*)
+  ERR_load_ATTIC_strings(void)
+  ERR_unload_ATTIC_strings(void)
+  ERR_ATTIC_error(int;int;char*;int)
+  sk_OSSL_STORE_INFO_num(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_value(structstack_st_OSSL_STORE_INFO*;int)
+  sk_OSSL_STORE_INFO_new(sk_OSSL_STORE_INFO_compfunc)
+  sk_OSSL_STORE_INFO_new_null(void)
+  sk_OSSL_STORE_INFO_new_reserve(sk_OSSL_STORE_INFO_compfunc;int)
+  sk_OSSL_STORE_INFO_reserve(structstack_st_OSSL_STORE_INFO*;int)
+  sk_OSSL_STORE_INFO_free(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_zero(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_delete(structstack_st_OSSL_STORE_INFO*;int)
+  sk_OSSL_STORE_INFO_delete_ptr(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_push(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_unshift(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_pop(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_shift(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_pop_free(structstack_st_OSSL_STORE_INFO*;sk_OSSL_STORE_INFO_freefunc)
+  sk_OSSL_STORE_INFO_insert(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*;int)
+  sk_OSSL_STORE_INFO_set(structstack_st_OSSL_STORE_INFO*;int;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_find(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_find_ex(structstack_st_OSSL_STORE_INFO*;OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_sort(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_is_sorted(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_dup(structstack_st_OSSL_STORE_INFO*)
+  sk_OSSL_STORE_INFO_deep_copy(structstack_st_OSSL_STORE_INFO*;sk_OSSL_STORE_INFO_copyfunc;sk_OSSL_STORE_INFO_freefunc)
+  sk_OSSL_STORE_INFO_set_cmp_func(structstack_st_OSSL_STORE_INFO*;sk_OSSL_STORE_INFO_compfunc)
+  file_get_pass(UI_METHOD*;char*;size_t;char*;char*;void*)
+  file_fill_pem_pass_data(structpem_pass_data*;char*;char*;UI_METHOD*;void*)
+  file_get_pem_pass(char*;int;int;void*)
+  check_suffix(char*;char*)
+  get0_EMBEDDED(OSSL_STORE_INFO*)
+  store_info_free(OSSL_STORE_INFO*)
+  new_EMBEDDED(char*;BUF_MEM*)
+  try_decode_PKCS12(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  eof_PKCS12(void*)
+  destroy_ctx_PKCS12(void*)
+  try_decode_PKCS8Encrypted(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  try_decode_PrivateKey(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  try_decode_PUBKEY(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  try_decode_params(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  try_decode_X509Certificate(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  try_decode_X509CRL(char*;char*;unsignedchar*;size_t;void*;int*;UI_METHOD*;void*;char*;OSSL_LIB_CTX*;char*)
+  OSSL_STORE_LOADER_CTX_free(OSSL_STORE_LOADER_CTX*)
+  file_find_type(OSSL_STORE_LOADER_CTX*)
+  file_open_ex(OSSL_STORE_LOADER*;char*;OSSL_LIB_CTX*;char*;UI_METHOD*;void*)
+  file_open(OSSL_STORE_LOADER*;char*;UI_METHOD*;void*)
+  file_attach(OSSL_STORE_LOADER*;BIO*;OSSL_LIB_CTX*;char*;UI_METHOD*;void*)
+  file_ctrl(OSSL_STORE_LOADER_CTX*;int;va_list)
+  file_expect(OSSL_STORE_LOADER_CTX*;int)
+  file_find(OSSL_STORE_LOADER_CTX*;OSSL_STORE_SEARCH*)
+  file_load_try_decode(OSSL_STORE_LOADER_CTX*;char*;char*;unsignedchar*;size_t;UI_METHOD*;void*;int*)
+  file_load_try_repeat(OSSL_STORE_LOADER_CTX*;UI_METHOD*;void*)
+  pem_free_flag(void*;int;size_t)
+  file_read_pem(BIO*;char*;char*;unsignedchar*;long*;UI_METHOD*;void*;char*;int)
+  file_try_read_msblob(BIO*;int*)
+  file_try_read_PVK(BIO*;UI_METHOD*;void*;char*;int*)
+  file_read_asn1(BIO*;unsignedchar*;long*)
+  file_name_to_uri(OSSL_STORE_LOADER_CTX*;char*;char*)
+  file_name_check(OSSL_STORE_LOADER_CTX*;char*)
+  file_load(OSSL_STORE_LOADER_CTX*;UI_METHOD*;void*)
+  file_error(OSSL_STORE_LOADER_CTX*)
+  file_eof(OSSL_STORE_LOADER_CTX*)
+  file_close(OSSL_STORE_LOADER_CTX*)
+  loader_attic_init(ENGINE*)
+  loader_attic_finish(ENGINE*)
+  loader_attic_destroy(ENGINE*)
+  bind_loader_attic(ENGINE*)
+  bind_helper(ENGINE*;char*)
+  v_check(unsignedlong)
+  bind_engine(ENGINE*;char*;dynamic_fns*)
} 
@enduml
