@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/thread/api.c.html#422]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/thread/api.c.html#424]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/thread/api.c.html#427]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#427]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/thread/api.c.html#427]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/thread/api.c.html#427]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/thread/api.c.html#427]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/thread/api.c.html#427]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/thread/api.c.html#758]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/thread/api.c.html#763]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/thread/api.c.html#770]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/thread/api.c.html#932]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/thread/api.c.html#947]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/thread/api.c.html#957]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/thread/api.c.html#969]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/thread/api.c.html#975]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/thread/api.c.html#981]]]
} 
@enduml
