@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/providers/common/securitycheck.c.html#783]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck.c.html#792]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck.c.html#802]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/providers/common/securitycheck.c.html#809]]]
putchar(int) :  int  [[[./../../.././qc/providers/common/securitycheck.c.html#818]]]
} 
@enduml
