@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#783]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#792]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#802]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#809]]]
putchar(int) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#818]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#827]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#837]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#844]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#850]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#857]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#876]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#889]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#908]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#922]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#943]]]
printf(char*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#950]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#962]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#972]]]
dprintf(int;char*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#987]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#998]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1017]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1043]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1070]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1668]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1673]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1680]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1779]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1794]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1804]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1816]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1822]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1828]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/providers/common/securitycheck_default.c.html#2481]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_BIO_type(BIO*) : BIO [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_BIO_compfunc_type(sk_BIO_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_BIO_freefunc_type(sk_BIO_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_X509_ALGOR_type(X509_ALGOR*) : X509_ALGOR [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_X509_ALGOR_compfunc_type(sk_X509_ALGOR_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_X509_ALGOR_copyfunc_type(sk_X509_ALGOR_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_X509_ALGOR_freefunc_type(sk_X509_ALGOR_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_type(ASN1_STRING_TABLE*) : ASN1_STRING_TABLE [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_compfunc_type(sk_ASN1_STRING_TABLE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_copyfunc_type(sk_ASN1_STRING_TABLE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_freefunc_type(sk_ASN1_STRING_TABLE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_TYPE_type(ASN1_TYPE*) : ASN1_TYPE [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_TYPE_compfunc_type(sk_ASN1_TYPE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_TYPE_copyfunc_type(sk_ASN1_TYPE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_TYPE_freefunc_type(sk_ASN1_TYPE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_OBJECT_type(ASN1_OBJECT*) : ASN1_OBJECT [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_OBJECT_compfunc_type(sk_ASN1_OBJECT_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_OBJECT_copyfunc_type(sk_ASN1_OBJECT_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_OBJECT_freefunc_type(sk_ASN1_OBJECT_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_INTEGER_type(ASN1_INTEGER*) : ASN1_INTEGER [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_INTEGER_compfunc_type(sk_ASN1_INTEGER_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_INTEGER_copyfunc_type(sk_ASN1_INTEGER_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_INTEGER_freefunc_type(sk_ASN1_INTEGER_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_UTF8STRING_type(ASN1_UTF8STRING*) : ASN1_UTF8STRING [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_UTF8STRING_compfunc_type(sk_ASN1_UTF8STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_UTF8STRING_copyfunc_type(sk_ASN1_UTF8STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_UTF8STRING_freefunc_type(sk_ASN1_UTF8STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_type(ASN1_GENERALSTRING*) : ASN1_GENERALSTRING [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_const_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_compfunc_type(sk_ASN1_GENERALSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_copyfunc_type(sk_ASN1_GENERALSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_freefunc_type(sk_ASN1_GENERALSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_securitycheck_enabled(OSSL_LIB_CTX*) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
ossl_digest_rsa_sign_get_md_nid(OSSL_LIB_CTX*;EVP_MD*;int) :  int  [[[./../../.././qc/providers/common/securitycheck_default.c.html#1]]]
} 
@enduml
