@startuml
!pragma layout smetana
class dummy {
CAST_ofb64_encrypt(unsignedchar*;unsignedchar*;long;CAST_KEY*;unsignedchar*;int*) :  void  [[[./../../.././qc/crypto/cast/c_ofb64.c.html#85]]]
} 
@enduml
