@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/ssl/statem/extensions_clnt.c.html#917]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/ssl/statem/extensions_clnt.c.html#926]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/ssl/statem/extensions_clnt.c.html#936]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/ssl/statem/extensions_clnt.c.html#943]]]
putchar(int) :  int  [[[./../../.././qc/ssl/statem/extensions_clnt.c.html#952]]]
} 
@enduml
