@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#310]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#317]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#358]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#366]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#373]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#386]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#393]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#400]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#408]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#418]]]
strcat(char*;char*) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#425]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#432]]]
getchar(void) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1307]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1316]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1326]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1333]]]
putchar(int) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1342]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1351]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1361]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1368]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1374]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1381]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1400]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1413]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1432]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1446]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1467]]]
printf(char*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1474]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1486]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1496]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1511]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1522]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1541]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1567]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1594]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1752]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1757]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1764]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1911]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1926]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1936]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1948]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1954]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/ct/ct_sct_ctx.c.html#1960]]]
} 
@enduml
