@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sha/sha256.c.html#194]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sha/sha256.c.html#199]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/sha/sha256.c.html#206]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/sha/sha256.c.html#506]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/sha/sha256.c.html#521]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/sha/sha256.c.html#531]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/sha/sha256.c.html#543]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/sha/sha256.c.html#549]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/sha/sha256.c.html#555]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/sha/sha256.c.html#1223]]]
} 
@enduml
