@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#769]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#778]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#788]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#795]]]
putchar(int) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#804]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#813]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#823]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#830]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#836]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#843]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#862]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#875]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#894]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#908]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#929]]]
printf(char*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#936]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#948]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#958]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#973]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#984]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1003]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1029]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1056]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1654]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1659]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1666]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1765]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1780]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1790]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1802]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1808]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1814]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#2467]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_BIO_type(BIO*) : BIO [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_BIO_sk_type(structstack_st_BIO*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_BIO_compfunc_type(sk_BIO_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_BIO_freefunc_type(sk_BIO_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_X509_ALGOR_type(X509_ALGOR*) : X509_ALGOR [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_X509_ALGOR_compfunc_type(sk_X509_ALGOR_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_X509_ALGOR_copyfunc_type(sk_X509_ALGOR_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_X509_ALGOR_freefunc_type(sk_X509_ALGOR_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_type(ASN1_STRING_TABLE*) : ASN1_STRING_TABLE [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_compfunc_type(sk_ASN1_STRING_TABLE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_copyfunc_type(sk_ASN1_STRING_TABLE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_STRING_TABLE_freefunc_type(sk_ASN1_STRING_TABLE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_TYPE_type(ASN1_TYPE*) : ASN1_TYPE [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_TYPE_compfunc_type(sk_ASN1_TYPE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_TYPE_copyfunc_type(sk_ASN1_TYPE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_TYPE_freefunc_type(sk_ASN1_TYPE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_OBJECT_type(ASN1_OBJECT*) : ASN1_OBJECT [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_OBJECT_compfunc_type(sk_ASN1_OBJECT_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_OBJECT_copyfunc_type(sk_ASN1_OBJECT_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_OBJECT_freefunc_type(sk_ASN1_OBJECT_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_INTEGER_type(ASN1_INTEGER*) : ASN1_INTEGER [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_INTEGER_compfunc_type(sk_ASN1_INTEGER_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_INTEGER_copyfunc_type(sk_ASN1_INTEGER_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_INTEGER_freefunc_type(sk_ASN1_INTEGER_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_UTF8STRING_type(ASN1_UTF8STRING*) : ASN1_UTF8STRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_UTF8STRING_compfunc_type(sk_ASN1_UTF8STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_UTF8STRING_copyfunc_type(sk_ASN1_UTF8STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_UTF8STRING_freefunc_type(sk_ASN1_UTF8STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_type(ASN1_GENERALSTRING*) : ASN1_GENERALSTRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_compfunc_type(sk_ASN1_GENERALSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_copyfunc_type(sk_ASN1_GENERALSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_GENERALSTRING_freefunc_type(sk_ASN1_GENERALSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_VALUE_type(ASN1_VALUE*) : ASN1_VALUE [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ASN1_VALUE_sk_type(structstack_st_ASN1_VALUE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_VALUE_sk_type(structstack_st_ASN1_VALUE*) : OPENSSL_STACK [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_VALUE_compfunc_type(sk_ASN1_VALUE_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_VALUE_copyfunc_type(sk_ASN1_VALUE_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ASN1_VALUE_freefunc_type(sk_ASN1_VALUE_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*) : OPENSSL_STRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_compfunc_type(lh_OPENSSL_STRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_hashfunc_type(lh_OPENSSL_STRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_STRING_lh_doallfunc_type(lh_OPENSSL_STRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*) : OPENSSL_CSTRING [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_compfunc_type(lh_OPENSSL_CSTRING_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_hashfunc_type(lh_OPENSSL_CSTRING_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_OPENSSL_CSTRING_lh_doallfunc_type(lh_OPENSSL_CSTRING_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ERR_GET_LIB(unsignedlong) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ERR_GET_RFLAGS(unsignedlong) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ERR_GET_REASON(unsignedlong) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ERR_FATAL_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ERR_COMMON_ERROR(unsignedlong) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*) : ERR_STRING_DATA [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_const_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*) : OPENSSL_LHASH [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_compfunc_type(lh_ERR_STRING_DATA_compfunc) : OPENSSL_LH_COMPFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_hashfunc_type(lh_ERR_STRING_DATA_hashfunc) : OPENSSL_LH_HASHFUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ossl_check_ERR_STRING_DATA_lh_doallfunc_type(lh_ERR_STRING_DATA_doallfunc) : OPENSSL_LH_DOALL_FUNC [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
BIO_new_NDEF(BIO*;ASN1_VALUE*;ASN1_ITEM*) : BIO [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ndef_prefix(BIO*;unsignedchar*;int*;void*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ndef_prefix_free(BIO*;unsignedchar*;int*;void*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ndef_suffix_free(BIO*;unsignedchar*;int*;void*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
ndef_suffix(BIO*;unsignedchar*;int*;void*) :  int  [[[./../../.././qc/crypto/asn1/bio_ndef.c.html#1]]]
} 
@enduml
