@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/asn1/tasn_fre.c.html#781]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/asn1/tasn_fre.c.html#790]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/asn1/tasn_fre.c.html#800]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/asn1/tasn_fre.c.html#807]]]
putchar(int) :  int  [[[./../../.././qc/crypto/asn1/tasn_fre.c.html#816]]]
} 
@enduml
