@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#183]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#188]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#195]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#495]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#510]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#520]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#532]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#538]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/asn1/tasn_prn.c.html#544]]]
} 
@enduml
