@startuml
!pragma layout smetana
class dummy {
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#327]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#342]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#352]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#364]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#370]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#376]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#979]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#981]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#984]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#1389]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#1394]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#1401]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/apps/lib/apps_opt_printf.c.html#1718]]]
} 
@enduml
