@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/apps/lib/apps.c.html#906]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/apps.c.html#915]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/apps.c.html#925]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/apps/lib/apps.c.html#932]]]
putchar(int) :  int  [[[./../../.././qc/apps/lib/apps.c.html#941]]]
} 
@enduml
