@startuml
 <|-- dummy.__locale_struct
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy._IO_marker
 <|-- dummy._IO_FILE
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.timeval
 <|-- dummy.timespec
 <|-- dummy.
 <|-- dummy.__pthread_rwlock_arch_t
 <|-- dummy.__pthread_internal_list
 <|-- dummy.__pthread_mutex_s
 <|-- dummy.__pthread_cond_s
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.pthread_attr_t
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.random_data
 <|-- dummy.drand48_data
 <|-- dummy.tm
 <|-- dummy.itimerspec
 <|-- dummy.
 <|-- dummy.crypto_ex_data_st
 <|-- dummy.crypto_threadid_st
 <|-- dummy.sched_param
 <|-- dummy.
 <|-- dummy._pthread_cleanup_buffer
 <|-- dummy.
 <|-- dummy.
 <|-- dummy.__pthread_cleanup_frame
 <|-- dummy.BIO_sock_info_u
 <|-- dummy.lhash_st_OPENSSL_STRING
 <|-- dummy.lh_OPENSSL_STRING_dummy
 <|-- dummy.lhash_st_OPENSSL_CSTRING
 <|-- dummy.lh_OPENSSL_CSTRING_dummy
 <|-- dummy.err_state_st
 <|-- dummy.ERR_string_data_st
 <|-- dummy.lhash_st_ERR_STRING_DATA
 <|-- dummy.lh_ERR_STRING_DATA_dummy
 <|-- dummy.
 <|-- dummy.ossl_dispatch_st
 <|-- dummy.ossl_item_st
 <|-- dummy.ossl_algorithm_st
 <|-- dummy.ossl_param_st
 <|-- dummy.asn1_string_st
 <|-- dummy.ASN1_ENCODING_st
 <|-- dummy.asn1_string_table_st
 <|-- dummy.asn1_type_st
 <|-- dummy.
 <|-- dummy.BIT_STRING_BITNAME_st
 <|-- dummy.obj_name_st
 <|-- dummy.
 <|-- dummy.evp_cipher_info_st
 <|-- dummy.buf_mem_st
 <|-- dummy.
 <|-- dummy.rsa_pss_params_st
 <|-- dummy.rsa_oaep_params_st
 <|-- dummy.SHAstate_st
 <|-- dummy.SHA256state_st
 <|-- dummy.SHA512state_st
 <|-- dummy.
 <|-- dummy.X509_algor_st
 <|-- dummy.X509_val_st
 <|-- dummy.x509_trust_st
 <|-- dummy.private_key_st
 <|-- dummy.X509_info_st
 <|-- dummy.Netscape_spkac_st
 <|-- dummy.Netscape_spki_st
 <|-- dummy.Netscape_certificate_sequence
 <|-- dummy.PBEPARAM_st
 <|-- dummy.PBE2PARAM_st
 <|-- dummy.PBKDF2PARAM_st
 <|-- dummy.SCRYPT_PARAMS_st
 <|-- dummy.PKCS7_CTX_st
 <|-- dummy.pkcs7_issuer_and_serial_st
 <|-- dummy.pkcs7_signer_info_st
 <|-- dummy.pkcs7_recip_info_st
 <|-- dummy.pkcs7_signed_st
 <|-- dummy.pkcs7_enc_content_st
 <|-- dummy.pkcs7_enveloped_st
 <|-- dummy.pkcs7_signedandenveloped_st
 <|-- dummy.pkcs7_digest_st
 <|-- dummy.pkcs7_encrypted_st
 <|-- dummy.pkcs7_st
 <|-- dummy.
 <|-- dummy.pw_cb_data
class dummy.pw_cb_data {
+  bcopy(void*;void*;size_t)
+  bzero(void*;size_t)
+  memcpy(void*;void*;size_t)
+  memmove(void*;void*;size_t)
+  memset(void*;int;size_t)
+  explicit_bzero(void*;size_t)
+  strcpy(char*;char*)
+  strncpy(char*;char*;size_t)
+  stpncpy(char*;char*;size_t)
+  strcat(char*;char*)
+  strncat(char*;char*;size_t)
+  strtoimax(char*;char*;int)
+  strtoumax(char*;char*;int)
+  wcstoimax(__gwchar_t*;__gwchar_t*;int)
+  wcstoumax(__gwchar_t*;__gwchar_t*;int)
+  getchar(void)
+  fgetc_unlocked(FILE*)
+  getc_unlocked(FILE*)
+  getchar_unlocked(void)
+  putchar(int)
+  fputc_unlocked(int;FILE*)
+  putc_unlocked(int;FILE*)
+  putchar_unlocked(int)
+  feof_unlocked(FILE*)
+  ferror_unlocked(FILE*)
+  sprintf(char*;char*)
+  vsprintf(char*;char*;__gnuc_va_list)
+  snprintf(char*;size_t;char*)
+  vsnprintf(char*;size_t;char*;__gnuc_va_list)
+  fprintf(FILE*;char*)
+  printf(char*)
+  vprintf(char*;__gnuc_va_list)
+  vfprintf(FILE*;char*;__gnuc_va_list)
+  dprintf(int;char*)
+  vdprintf(int;char*;__gnuc_va_list)
+  fgets(char*;int;FILE*)
+  fread(void*;size_t;size_t;FILE*)
+  fread_unlocked(void*;size_t;size_t;FILE*)
+  atoi(char*)
+  atol(char*)
+  atoll(char*)
+  __bswap_32(unsignedint)
+  __bswap_64(__uint64_t)
+  __uint16_identity(__uint16_t)
+  __uint32_identity(__uint32_t)
+  __uint64_identity(__uint64_t)
+  gnu_dev_major(__dev_t)
+  gnu_dev_minor(__dev_t)
+  gnu_dev_makedev(unsignedint;unsignedint)
+  bsearch(void*;void*;size_t;size_t;__compar_fn_t)
+  atof(char*)
+  realpath(char*;char*)
+  ptsname_r(int;char*;size_t)
+  wctomb(char*;wchar_t)
+  mbstowcs(wchar_t*;char*;size_t)
+  wcstombs(char*;wchar_t*;size_t)
+  ossl_check_OPENSSL_STRING_type(char*)
+  ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc)
+  ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc)
+  ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc)
+  ossl_check_OPENSSL_CSTRING_type(char*)
+  ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc)
+  ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc)
+  ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc)
+  ossl_check_OPENSSL_BLOCK_type(void*)
+  ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*)
+  ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*)
+  ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc)
+  ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc)
+  ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc)
+  ossl_check_void_type(void*)
+  ossl_check_const_void_sk_type(structstack_st_void*)
+  ossl_check_void_sk_type(structstack_st_void*)
+  ossl_check_void_compfunc_type(sk_void_compfunc)
+  ossl_check_void_copyfunc_type(sk_void_copyfunc)
+  ossl_check_void_freefunc_type(sk_void_freefunc)
+  pthread_equal(pthread_t;pthread_t)
+  ossl_check_BIO_type(BIO*)
+  ossl_check_const_BIO_sk_type(structstack_st_BIO*)
+  ossl_check_BIO_sk_type(structstack_st_BIO*)
+  ossl_check_BIO_compfunc_type(sk_BIO_compfunc)
+  ossl_check_BIO_copyfunc_type(sk_BIO_copyfunc)
+  ossl_check_BIO_freefunc_type(sk_BIO_freefunc)
+  ossl_check_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*)
+  ossl_check_const_OPENSSL_STRING_lh_plain_type(OPENSSL_STRING*)
+  ossl_check_const_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_lh_type(structlhash_st_OPENSSL_STRING*)
+  ossl_check_OPENSSL_STRING_lh_compfunc_type(lh_OPENSSL_STRING_compfunc)
+  ossl_check_OPENSSL_STRING_lh_hashfunc_type(lh_OPENSSL_STRING_hashfunc)
+  ossl_check_OPENSSL_STRING_lh_doallfunc_type(lh_OPENSSL_STRING_doallfunc)
+  ossl_check_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*)
+  ossl_check_const_OPENSSL_CSTRING_lh_plain_type(OPENSSL_CSTRING*)
+  ossl_check_const_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_lh_type(structlhash_st_OPENSSL_CSTRING*)
+  ossl_check_OPENSSL_CSTRING_lh_compfunc_type(lh_OPENSSL_CSTRING_compfunc)
+  ossl_check_OPENSSL_CSTRING_lh_hashfunc_type(lh_OPENSSL_CSTRING_hashfunc)
+  ossl_check_OPENSSL_CSTRING_lh_doallfunc_type(lh_OPENSSL_CSTRING_doallfunc)
+  ERR_GET_LIB(unsignedlong)
+  ERR_GET_FUNC(unsignedlong)
+  ERR_GET_RFLAGS(unsignedlong)
+  ERR_GET_REASON(unsignedlong)
+  ERR_FATAL_ERROR(unsignedlong)
+  ERR_COMMON_ERROR(unsignedlong)
+  ossl_check_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*)
+  ossl_check_const_ERR_STRING_DATA_lh_plain_type(ERR_STRING_DATA*)
+  ossl_check_const_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*)
+  ossl_check_ERR_STRING_DATA_lh_type(structlhash_st_ERR_STRING_DATA*)
+  ossl_check_ERR_STRING_DATA_lh_compfunc_type(lh_ERR_STRING_DATA_compfunc)
+  ossl_check_ERR_STRING_DATA_lh_hashfunc_type(lh_ERR_STRING_DATA_hashfunc)
+  ossl_check_ERR_STRING_DATA_lh_doallfunc_type(lh_ERR_STRING_DATA_doallfunc)
+  ossl_check_X509_ALGOR_type(X509_ALGOR*)
+  ossl_check_const_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*)
+  ossl_check_X509_ALGOR_sk_type(structstack_st_X509_ALGOR*)
+  ossl_check_X509_ALGOR_compfunc_type(sk_X509_ALGOR_compfunc)
+  ossl_check_X509_ALGOR_copyfunc_type(sk_X509_ALGOR_copyfunc)
+  ossl_check_X509_ALGOR_freefunc_type(sk_X509_ALGOR_freefunc)
+  ossl_check_ASN1_STRING_TABLE_type(ASN1_STRING_TABLE*)
+  ossl_check_const_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*)
+  ossl_check_ASN1_STRING_TABLE_sk_type(structstack_st_ASN1_STRING_TABLE*)
+  ossl_check_ASN1_STRING_TABLE_compfunc_type(sk_ASN1_STRING_TABLE_compfunc)
+  ossl_check_ASN1_STRING_TABLE_copyfunc_type(sk_ASN1_STRING_TABLE_copyfunc)
+  ossl_check_ASN1_STRING_TABLE_freefunc_type(sk_ASN1_STRING_TABLE_freefunc)
+  ossl_check_ASN1_TYPE_type(ASN1_TYPE*)
+  ossl_check_const_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*)
+  ossl_check_ASN1_TYPE_sk_type(structstack_st_ASN1_TYPE*)
+  ossl_check_ASN1_TYPE_compfunc_type(sk_ASN1_TYPE_compfunc)
+  ossl_check_ASN1_TYPE_copyfunc_type(sk_ASN1_TYPE_copyfunc)
+  ossl_check_ASN1_TYPE_freefunc_type(sk_ASN1_TYPE_freefunc)
+  ossl_check_ASN1_OBJECT_type(ASN1_OBJECT*)
+  ossl_check_const_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*)
+  ossl_check_ASN1_OBJECT_sk_type(structstack_st_ASN1_OBJECT*)
+  ossl_check_ASN1_OBJECT_compfunc_type(sk_ASN1_OBJECT_compfunc)
+  ossl_check_ASN1_OBJECT_copyfunc_type(sk_ASN1_OBJECT_copyfunc)
+  ossl_check_ASN1_OBJECT_freefunc_type(sk_ASN1_OBJECT_freefunc)
+  ossl_check_ASN1_INTEGER_type(ASN1_INTEGER*)
+  ossl_check_const_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*)
+  ossl_check_ASN1_INTEGER_sk_type(structstack_st_ASN1_INTEGER*)
+  ossl_check_ASN1_INTEGER_compfunc_type(sk_ASN1_INTEGER_compfunc)
+  ossl_check_ASN1_INTEGER_copyfunc_type(sk_ASN1_INTEGER_copyfunc)
+  ossl_check_ASN1_INTEGER_freefunc_type(sk_ASN1_INTEGER_freefunc)
+  ossl_check_ASN1_UTF8STRING_type(ASN1_UTF8STRING*)
+  ossl_check_const_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*)
+  ossl_check_ASN1_UTF8STRING_sk_type(structstack_st_ASN1_UTF8STRING*)
+  ossl_check_ASN1_UTF8STRING_compfunc_type(sk_ASN1_UTF8STRING_compfunc)
+  ossl_check_ASN1_UTF8STRING_copyfunc_type(sk_ASN1_UTF8STRING_copyfunc)
+  ossl_check_ASN1_UTF8STRING_freefunc_type(sk_ASN1_UTF8STRING_freefunc)
+  ossl_check_ASN1_GENERALSTRING_type(ASN1_GENERALSTRING*)
+  ossl_check_const_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*)
+  ossl_check_ASN1_GENERALSTRING_sk_type(structstack_st_ASN1_GENERALSTRING*)
+  ossl_check_ASN1_GENERALSTRING_compfunc_type(sk_ASN1_GENERALSTRING_compfunc)
+  ossl_check_ASN1_GENERALSTRING_copyfunc_type(sk_ASN1_GENERALSTRING_copyfunc)
+  ossl_check_ASN1_GENERALSTRING_freefunc_type(sk_ASN1_GENERALSTRING_freefunc)
+  ossl_check_X509_NAME_type(X509_NAME*)
+  ossl_check_const_X509_NAME_sk_type(structstack_st_X509_NAME*)
+  ossl_check_X509_NAME_sk_type(structstack_st_X509_NAME*)
+  ossl_check_X509_NAME_compfunc_type(sk_X509_NAME_compfunc)
+  ossl_check_X509_NAME_copyfunc_type(sk_X509_NAME_copyfunc)
+  ossl_check_X509_NAME_freefunc_type(sk_X509_NAME_freefunc)
+  ossl_check_X509_type(X509*)
+  ossl_check_const_X509_sk_type(structstack_st_X509*)
+  ossl_check_X509_sk_type(structstack_st_X509*)
+  ossl_check_X509_compfunc_type(sk_X509_compfunc)
+  ossl_check_X509_copyfunc_type(sk_X509_copyfunc)
+  ossl_check_X509_freefunc_type(sk_X509_freefunc)
+  ossl_check_X509_REVOKED_type(X509_REVOKED*)
+  ossl_check_const_X509_REVOKED_sk_type(structstack_st_X509_REVOKED*)
+  ossl_check_X509_REVOKED_sk_type(structstack_st_X509_REVOKED*)
+  ossl_check_X509_REVOKED_compfunc_type(sk_X509_REVOKED_compfunc)
+  ossl_check_X509_REVOKED_copyfunc_type(sk_X509_REVOKED_copyfunc)
+  ossl_check_X509_REVOKED_freefunc_type(sk_X509_REVOKED_freefunc)
+  ossl_check_X509_CRL_type(X509_CRL*)
+  ossl_check_const_X509_CRL_sk_type(structstack_st_X509_CRL*)
+  ossl_check_X509_CRL_sk_type(structstack_st_X509_CRL*)
+  ossl_check_X509_CRL_compfunc_type(sk_X509_CRL_compfunc)
+  ossl_check_X509_CRL_copyfunc_type(sk_X509_CRL_copyfunc)
+  ossl_check_X509_CRL_freefunc_type(sk_X509_CRL_freefunc)
+  ossl_check_X509_NAME_ENTRY_type(X509_NAME_ENTRY*)
+  ossl_check_const_X509_NAME_ENTRY_sk_type(structstack_st_X509_NAME_ENTRY*)
+  ossl_check_X509_NAME_ENTRY_sk_type(structstack_st_X509_NAME_ENTRY*)
+  ossl_check_X509_NAME_ENTRY_compfunc_type(sk_X509_NAME_ENTRY_compfunc)
+  ossl_check_X509_NAME_ENTRY_copyfunc_type(sk_X509_NAME_ENTRY_copyfunc)
+  ossl_check_X509_NAME_ENTRY_freefunc_type(sk_X509_NAME_ENTRY_freefunc)
+  ossl_check_X509_EXTENSION_type(X509_EXTENSION*)
+  ossl_check_const_X509_EXTENSION_sk_type(structstack_st_X509_EXTENSION*)
+  ossl_check_X509_EXTENSION_sk_type(structstack_st_X509_EXTENSION*)
+  ossl_check_X509_EXTENSION_compfunc_type(sk_X509_EXTENSION_compfunc)
+  ossl_check_X509_EXTENSION_copyfunc_type(sk_X509_EXTENSION_copyfunc)
+  ossl_check_X509_EXTENSION_freefunc_type(sk_X509_EXTENSION_freefunc)
+  ossl_check_X509_ATTRIBUTE_type(X509_ATTRIBUTE*)
+  ossl_check_const_X509_ATTRIBUTE_sk_type(structstack_st_X509_ATTRIBUTE*)
+  ossl_check_X509_ATTRIBUTE_sk_type(structstack_st_X509_ATTRIBUTE*)
+  ossl_check_X509_ATTRIBUTE_compfunc_type(sk_X509_ATTRIBUTE_compfunc)
+  ossl_check_X509_ATTRIBUTE_copyfunc_type(sk_X509_ATTRIBUTE_copyfunc)
+  ossl_check_X509_ATTRIBUTE_freefunc_type(sk_X509_ATTRIBUTE_freefunc)
+  ossl_check_X509_TRUST_type(X509_TRUST*)
+  ossl_check_const_X509_TRUST_sk_type(structstack_st_X509_TRUST*)
+  ossl_check_X509_TRUST_sk_type(structstack_st_X509_TRUST*)
+  ossl_check_X509_TRUST_compfunc_type(sk_X509_TRUST_compfunc)
+  ossl_check_X509_TRUST_copyfunc_type(sk_X509_TRUST_copyfunc)
+  ossl_check_X509_TRUST_freefunc_type(sk_X509_TRUST_freefunc)
+  ossl_check_X509_INFO_type(X509_INFO*)
+  ossl_check_const_X509_INFO_sk_type(structstack_st_X509_INFO*)
+  ossl_check_X509_INFO_sk_type(structstack_st_X509_INFO*)
+  ossl_check_X509_INFO_compfunc_type(sk_X509_INFO_compfunc)
+  ossl_check_X509_INFO_copyfunc_type(sk_X509_INFO_copyfunc)
+  ossl_check_X509_INFO_freefunc_type(sk_X509_INFO_freefunc)
+  ossl_check_X509_LOOKUP_type(X509_LOOKUP*)
+  ossl_check_const_X509_LOOKUP_sk_type(structstack_st_X509_LOOKUP*)
+  ossl_check_X509_LOOKUP_sk_type(structstack_st_X509_LOOKUP*)
+  ossl_check_X509_LOOKUP_compfunc_type(sk_X509_LOOKUP_compfunc)
+  ossl_check_X509_LOOKUP_copyfunc_type(sk_X509_LOOKUP_copyfunc)
+  ossl_check_X509_LOOKUP_freefunc_type(sk_X509_LOOKUP_freefunc)
+  ossl_check_X509_OBJECT_type(X509_OBJECT*)
+  ossl_check_const_X509_OBJECT_sk_type(structstack_st_X509_OBJECT*)
+  ossl_check_X509_OBJECT_sk_type(structstack_st_X509_OBJECT*)
+  ossl_check_X509_OBJECT_compfunc_type(sk_X509_OBJECT_compfunc)
+  ossl_check_X509_OBJECT_copyfunc_type(sk_X509_OBJECT_copyfunc)
+  ossl_check_X509_OBJECT_freefunc_type(sk_X509_OBJECT_freefunc)
+  ossl_check_X509_VERIFY_PARAM_type(X509_VERIFY_PARAM*)
+  ossl_check_const_X509_VERIFY_PARAM_sk_type(structstack_st_X509_VERIFY_PARAM*)
+  ossl_check_X509_VERIFY_PARAM_sk_type(structstack_st_X509_VERIFY_PARAM*)
+  ossl_check_X509_VERIFY_PARAM_compfunc_type(sk_X509_VERIFY_PARAM_compfunc)
+  ossl_check_X509_VERIFY_PARAM_copyfunc_type(sk_X509_VERIFY_PARAM_copyfunc)
+  ossl_check_X509_VERIFY_PARAM_freefunc_type(sk_X509_VERIFY_PARAM_freefunc)
+  ossl_check_PKCS7_SIGNER_INFO_type(PKCS7_SIGNER_INFO*)
+  ossl_check_const_PKCS7_SIGNER_INFO_sk_type(structstack_st_PKCS7_SIGNER_INFO*)
+  ossl_check_PKCS7_SIGNER_INFO_sk_type(structstack_st_PKCS7_SIGNER_INFO*)
+  ossl_check_PKCS7_SIGNER_INFO_compfunc_type(sk_PKCS7_SIGNER_INFO_compfunc)
+  ossl_check_PKCS7_SIGNER_INFO_copyfunc_type(sk_PKCS7_SIGNER_INFO_copyfunc)
+  ossl_check_PKCS7_SIGNER_INFO_freefunc_type(sk_PKCS7_SIGNER_INFO_freefunc)
+  ossl_check_PKCS7_RECIP_INFO_type(PKCS7_RECIP_INFO*)
+  ossl_check_const_PKCS7_RECIP_INFO_sk_type(structstack_st_PKCS7_RECIP_INFO*)
+  ossl_check_PKCS7_RECIP_INFO_sk_type(structstack_st_PKCS7_RECIP_INFO*)
+  ossl_check_PKCS7_RECIP_INFO_compfunc_type(sk_PKCS7_RECIP_INFO_compfunc)
+  ossl_check_PKCS7_RECIP_INFO_copyfunc_type(sk_PKCS7_RECIP_INFO_copyfunc)
+  ossl_check_PKCS7_RECIP_INFO_freefunc_type(sk_PKCS7_RECIP_INFO_freefunc)
+  ossl_check_PKCS7_type(PKCS7*)
+  ossl_check_const_PKCS7_sk_type(structstack_st_PKCS7*)
+  ossl_check_PKCS7_sk_type(structstack_st_PKCS7*)
+  ossl_check_PKCS7_compfunc_type(sk_PKCS7_compfunc)
+  ossl_check_PKCS7_copyfunc_type(sk_PKCS7_copyfunc)
+  ossl_check_PKCS7_freefunc_type(sk_PKCS7_freefunc)
+  ossl_check_UI_STRING_type(UI_STRING*)
+  ossl_check_const_UI_STRING_sk_type(structstack_st_UI_STRING*)
+  ossl_check_UI_STRING_sk_type(structstack_st_UI_STRING*)
+  ossl_check_UI_STRING_compfunc_type(sk_UI_STRING_compfunc)
+  ossl_check_UI_STRING_copyfunc_type(sk_UI_STRING_copyfunc)
+  ossl_check_UI_STRING_freefunc_type(sk_UI_STRING_freefunc)
+  ui_open(UI*)
+  ui_read(UI*;UI_STRING*)
+  ui_write(UI*;UI_STRING*)
+  ui_close(UI*)
+  ui_prompt_construct(UI*;char*;char*)
+  set_base_ui_method(UI_METHOD*)
+  setup_ui_method(void)
+  destroy_ui_method(void)
+  get_ui_method(void)
+  ui_malloc(int;char*)
+  password_callback(char*;int;int;PW_CB_DATA*)
} 
@enduml
