@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#298]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#305]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#346]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#354]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#361]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#374]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#381]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#388]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#396]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#406]]]
strcat(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#413]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#420]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#896]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#901]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#908]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/columns.c.html#1070]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/columns.c.html#1085]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/columns.c.html#1095]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/columns.c.html#1107]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/columns.c.html#1113]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/columns.c.html#1119]]]
} 
@enduml
