@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#298]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#305]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#346]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#354]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#361]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#374]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#381]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#388]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#396]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#406]]]
strcat(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#413]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#420]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#896]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#901]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#908]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/columns.c.html#1070]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/columns.c.html#1085]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/columns.c.html#1095]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/columns.c.html#1107]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/columns.c.html#1113]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/columns.c.html#1119]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/apps/lib/columns.c.html#1787]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#18793]]]
realpath(char*;char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getchar(void) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
putchar(int) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
printf(char*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
dprintf(int;char*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/columns.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
read(int;void*;size_t) : ssize_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
pread(int;void*;size_t;__off_t) : ssize_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
readlink(char*;char*;size_t) : ssize_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
readlinkat(int;char*;char*;size_t) : ssize_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getcwd(char*;size_t) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getwd(char*) :  char  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
confstr(int;char*;size_t) : size_t [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getgroups(int;__gid_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ttyname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getlogin_r(char*;size_t) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
gethostname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
getdomainname(char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_ends_with_dirsep(char*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
ossl_is_absolute_path(char*) :  int  [[[./../../.././qc/apps/lib/columns.c.html#1]]]
} 
@enduml
