@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/apps/lib/log.c.html#907]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/log.c.html#916]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/apps/lib/log.c.html#926]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/apps/lib/log.c.html#933]]]
putchar(int) :  int  [[[./../../.././qc/apps/lib/log.c.html#942]]]
} 
@enduml
