@startuml
!pragma layout smetana
class dummy {
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/opt.c.html#327]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/opt.c.html#342]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/opt.c.html#352]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/apps/lib/opt.c.html#364]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/apps/lib/opt.c.html#370]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/apps/lib/opt.c.html#376]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/opt.c.html#979]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/opt.c.html#981]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/apps/lib/opt.c.html#984]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#984]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/apps/lib/opt.c.html#984]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/apps/lib/opt.c.html#984]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/apps/lib/opt.c.html#984]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/apps/lib/opt.c.html#984]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/opt.c.html#1537]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/opt.c.html#1544]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/opt.c.html#1585]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/apps/lib/opt.c.html#1593]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/apps/lib/opt.c.html#1600]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/apps/lib/opt.c.html#1613]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/opt.c.html#1620]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/apps/lib/opt.c.html#1627]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/apps/lib/opt.c.html#1635]]]
} 
@enduml
