@startuml
!pragma layout smetana
class dummy {
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#455]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#457]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#460]]]
getchar(void) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1293]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1302]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1312]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1319]]]
putchar(int) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1328]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1337]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1347]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1354]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1360]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1367]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1386]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1399]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1418]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1432]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1453]]]
printf(char*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1460]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1472]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1482]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1497]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1508]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1527]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1553]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1580]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1751]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1756]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1763]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1910]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1925]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1935]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1947]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1953]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#1959]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/evp/dh_ctrl.c.html#2627]]]
} 
@enduml
