@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#915]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#924]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#934]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#941]]]
putchar(int) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#950]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#959]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#969]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#976]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#982]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#989]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1008]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1021]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1040]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1054]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1075]]]
printf(char*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1082]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1094]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1104]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1119]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1130]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1149]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1175]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1202]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1362]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1367]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1374]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1521]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1536]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1546]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1558]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1564]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#1570]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/evp/ec_ctrl.c.html#2238]]]
} 
@enduml
