@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#177]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#182]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#189]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#489]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#504]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#514]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#526]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#532]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/evp/keymgmt_lib.c.html#538]]]
} 
@enduml
