@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/evp/mac_meth.c.html#771]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/mac_meth.c.html#780]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/evp/mac_meth.c.html#790]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/evp/mac_meth.c.html#797]]]
putchar(int) :  int  [[[./../../.././qc/crypto/evp/mac_meth.c.html#806]]]
} 
@enduml
