@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/engine/eng_rdrand.c.html#762]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/engine/eng_rdrand.c.html#771]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/engine/eng_rdrand.c.html#781]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/engine/eng_rdrand.c.html#788]]]
putchar(int) :  int  [[[./../../.././qc/crypto/engine/eng_rdrand.c.html#797]]]
} 
@enduml
