@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#909]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#918]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#928]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#935]]]
putchar(int) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#944]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#953]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#963]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#970]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#976]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#983]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1002]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1015]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1034]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1048]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1069]]]
printf(char*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1076]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1088]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1098]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1113]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1124]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1143]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1169]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1196]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1368]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1373]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1380]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1527]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1542]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1552]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1564]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1570]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/engine/tb_cipher.c.html#1576]]]
} 
@enduml
