@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#171]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#176]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#183]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#483]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#498]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#508]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#520]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#526]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/kdfs/kbkdf.c.html#532]]]
} 
@enduml
