@startuml
!pragma layout smetana
class dummy {
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#300]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#307]]]
memcpy(void*;void*;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#348]]]
memmove(void*;void*;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#356]]]
memset(void*;int;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#363]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#376]]]
strcpy(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#383]]]
stpcpy(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#390]]]
strncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#398]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#408]]]
strcat(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#415]]]
strncat(char*;char*;size_t) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#422]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#586]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#591]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#598]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#898]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#913]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#923]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#935]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#941]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#947]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1615]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
getchar(void) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fgetc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
getc_unlocked(FILE*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
getchar_unlocked(void) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
putchar(int) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
putc_unlocked(int;FILE*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
putchar_unlocked(int) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fprintf(FILE*;char*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
printf(char*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
dprintf(int;char*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fgets(char*;int;FILE*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
pthread_equal(pthread_t;pthread_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
load32(uint8_t*) : uint32_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
load64(uint8_t*) : uint64_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
store32(uint8_t*;uint32_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
store64(uint8_t*;uint64_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
load48(uint8_t*) : uint64_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
store48(uint8_t*;uint64_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
rotr32(uint32_t;unsignedint) : uint32_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
rotr64(uint64_t;unsignedint) : uint64_t [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
blake2s_set_lastblock(BLAKE2S_CTX*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
blake2s_init0(BLAKE2S_CTX*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
blake2s_init_param(BLAKE2S_CTX*;BLAKE2S_PARAM*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_param_init(BLAKE2S_PARAM*) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_param_set_digest_length(BLAKE2S_PARAM*;uint8_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_param_set_key_length(BLAKE2S_PARAM*;uint8_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_param_set_personal(BLAKE2S_PARAM*;uint8_t*;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_param_set_salt(BLAKE2S_PARAM*;uint8_t*;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_init(BLAKE2S_CTX*;BLAKE2S_PARAM*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_init_key(BLAKE2S_CTX*;BLAKE2S_PARAM*;void*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
blake2s_compress(BLAKE2S_CTX*;uint8_t*;size_t) :  void  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_update(BLAKE2S_CTX*;void*;size_t) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
ossl_blake2s_final(unsignedchar*;BLAKE2S_CTX*) :  int  [[[./../../../.././qc/providers/implementations/digests/blake2s_prov.c.html#1]]]
} 
@enduml
