@startuml
!pragma layout smetana
class dummy {
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#191]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#196]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#203]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#503]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#518]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#528]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#540]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#546]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../../.././qc/providers/implementations/digests/null_prov.c.html#552]]]
} 
@enduml
