@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#905]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#914]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#924]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#931]]]
putchar(int) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#940]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#949]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#959]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#966]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#972]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#979]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#998]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1011]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1030]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1044]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1065]]]
printf(char*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1072]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1084]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1094]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1109]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1120]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1139]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1165]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1192]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1365]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1370]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1377]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1524]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1539]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1549]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1561]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1567]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#1573]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/encode_decode/encoder_lib.c.html#2241]]]
} 
@enduml
