@startuml
!pragma layout smetana
class dummy {
IDEA_cbc_encrypt(unsignedchar*;unsignedchar*;long;IDEA_KEY_SCHEDULE*;unsignedchar*;int) :  void  [[[./../../.././qc/crypto/idea/i_cbc.c.html#76]]]
IDEA_encrypt(unsignedlong*;IDEA_KEY_SCHEDULE*) :  void  [[[./../../.././qc/crypto/idea/i_cbc.c.html#152]]]
} 
@enduml
