@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#762]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#771]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#781]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#788]]]
putchar(int) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#797]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#806]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#816]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#823]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#829]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#836]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#855]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#868]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#887]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#901]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#922]]]
printf(char*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#929]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#941]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#951]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#966]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_depr.c.html#977]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#996]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1022]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1049]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1506]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1511]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1518]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1623]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1638]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1648]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1660]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1666]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1672]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#2325]]]
atof(char*) :  double  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
realpath(char*;char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ptsname_r(int;char*;size_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
wctomb(char*;wchar_t) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
mbstowcs(wchar_t*;char*;size_t) : size_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
wcstombs(char*;wchar_t*;size_t) : size_t [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
bcopy(void*;void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
memcpy(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
memmove(void*;void*;size_t) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
memset(void*;int;size_t) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
explicit_bzero(void*;size_t) :  void  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
strcpy(char*;char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
stpcpy(char*;char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
strncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
stpncpy(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
strcat(char*;char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
strncat(char*;char*;size_t) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_STRING_type(char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_const_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_STRING_sk_type(structstack_st_OPENSSL_STRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_STRING_compfunc_type(sk_OPENSSL_STRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_STRING_copyfunc_type(sk_OPENSSL_STRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_STRING_freefunc_type(sk_OPENSSL_STRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_CSTRING_type(char*) :  char  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_const_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_CSTRING_sk_type(structstack_st_OPENSSL_CSTRING*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_CSTRING_compfunc_type(sk_OPENSSL_CSTRING_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_CSTRING_copyfunc_type(sk_OPENSSL_CSTRING_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_CSTRING_freefunc_type(sk_OPENSSL_CSTRING_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_BLOCK_type(void*) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_const_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_BLOCK_sk_type(structstack_st_OPENSSL_BLOCK*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_BLOCK_compfunc_type(sk_OPENSSL_BLOCK_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_BLOCK_copyfunc_type(sk_OPENSSL_BLOCK_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_OPENSSL_BLOCK_freefunc_type(sk_OPENSSL_BLOCK_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_void_type(void*) :  void  [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_const_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_void_sk_type(structstack_st_void*) : OPENSSL_STACK [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_void_compfunc_type(sk_void_compfunc) : OPENSSL_sk_compfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_void_copyfunc_type(sk_void_copyfunc) : OPENSSL_sk_copyfunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
ossl_check_void_freefunc_type(sk_void_freefunc) : OPENSSL_sk_freefunc [[[./../../.././qc/crypto/bn/bn_depr.c.html#1]]]
} 
@enduml
