@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#786]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#795]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#805]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#812]]]
putchar(int) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#821]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#830]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#840]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#847]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#853]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#860]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#879]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#892]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#911]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#925]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#946]]]
printf(char*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#953]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#965]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#975]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#990]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1001]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1020]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1046]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1073]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1241]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1246]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1253]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1406]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1421]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1431]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1443]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1449]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#1455]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/bn/bn_gf2m.c.html#2123]]]
} 
@enduml
