name: C/C++ CI Complet

on:
  [push]
jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Dependencies graphviz pour plantuml
      run: |
          sudo apt-get install graphviz
    - name: Checkout du code source
      uses: actions/checkout@v1
    - name: lister
      run: ls -l
    - name: Verif maven
      run: mvn -U clean
    - name: lister
      run: ls -l
    - name: configure avec generation des template seul
      run: ./config -no-asm -E
    - name: make depend
      run: make depend
    - name: make
      run: make
    - name: Maven and co qcrgoalfileclonecpp
      run: mvn -U qcr:qcrgoalfileclonecpp
    - name: Maven and co compile
      run: mvn -Dsonar.debugskipxsl=true qcr:qcrgoalcompile
    - name: Maven and co mvn qcr:qcrgoalfilecopycpp
      run: mvn qcr:qcrgoalfilecopycpp
    - name: Maven and co mvn clean
      run: mvn clean qcr:qcrgoalclean
    - name: Maven and co ls
      run: ls -l # ne sert plus depuis 2019 12 29 rm  secucpp/qcrutils.c
    - name: Compilation qcrutils3
      run: gcc -fPIC -pthread -m64 -Wall -O3 -c -o secucpp/qcrutils3.o secucpp/qcrutils3.c 
    - name: Creation library shared libqcrutils3
      run: gcc -fPIC -pthread -m64 -Wall -O3 -Wl,-znodelete -shared  -Wl,-Bsymbolic -Wl,-soname=secucpp/libqcrutils3.so -o secucpp/libqcrutils3.so secucpp/qcrutils3.o
    - name: ls secucpp avant
      run: ls -l secucpp
    - name: Chmod sur libqcrutils3
      run: chmod -R 555 libqcrutils3.so
    - name: ls secucpp apres
      run: ls -l secucpp
    - name: Maven and co config. Modif D.C. 2021 03 30 ajt librarie
      run: ./config -no-asm -Wl,-rpath,/home/runner/work/openssl/openssl/secucpp/ -L/home/runner/work/openssl/openssl/secucpp/ -lqcrutils3
    - name: Maven and co make depend
      run: make depend
    - name: Maven and co rm
      run: rm -f /openssl/test/*.o
    - name: more crypto/ocsp/ocsp_vfy.c
      run: more crypto/ocsp/ocsp_vfy.c
    - name: more crypto/ocsp/v3_ocsp.c
      run: more crypto/ocsp/v3_ocsp.c
    - name: more crypto/mem.c
      run: more crypto/mem.c
    - name: Maven and co make
      run: make
    - name: ls -l
      run: ls -l
    - name: ls -l apps
      run: ls -l apps
    - name: ls -l crypto
      run: ls -l crypto
    - name: ls -l crypto/bio
      run: ls -l crypto/bio
    - name: Run maven site
      run: mvn site -Dsonar.reporting01nodocgeneration=yes
    - uses: actions/upload-artifact@v2
      with:
        name: ArtifactMvnSite
        path: |
           target/site
    - name: make test01
      # run: make test 2> ./make_test_err.log
      # V=1 : mode verbose
      run: make V=1 TESTS=01 test 2>> ./make_test_err80.log
    - name: ls -l 
      run: ls -l 
    - name: ls -lR 
      run: ls -lR "$PWD/"*
    - name: Maven and co sort
      run: sort -u -o make_test_err_sort.log make_test_err*.log
    - name: ls
      run: ls -l make_test_err_sort.log
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-sauve-log
        path: make_test_err_sort.log
    - uses: actions/upload-artifact@v2
      with:
        name: ArtifactTestRuns
        path: |
           test-runs
           !test-runs/**/*:*
    
