name: C/C++ CI Complet

on:
  [push]
jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Dependencies graphviz pour plantuml
      run: |
          sudo apt-get install graphviz
    - name: Checkout du code source
      uses: actions/checkout@v1
    - name: lister
      run: ls -l
    - name: Verif maven
      run: mvn -U clean
    - name: lister
      run: ls -l
    - name: configure avec generation des template seul
      run: ./config -no-asm -E
    - name: make depend
      run: make depend
    - name: make
      run: make
    - name: Maven and co qcrgoalfileclonecpp
      run: mvn -U qcr:qcrgoalfileclonecpp
    - name: Maven and co compile
      run: mvn -Dsonar.debugskipxsl=true qcr:qcrgoalcompile
    - name: Maven and co mvn qcr:qcrgoalfilecopycpp
      run: mvn qcr:qcrgoalfilecopycpp
    - name: Maven and co mvn clean
      run: mvn clean
    - name: Maven and co ls
      run: ls -l # ne sert plus depuis 2019 12 29 rm  secucpp/qcrutils.c
    - name: Maven and co config
      run: ./config -no-asm
    - name: Maven and co make depend
      run: make depend
    - name: Maven and co rm
      run: rm -f /openssl/test/*.o
    - name: more crypto/ocsp/ocsp_vfy.c
      run: more crypto/ocsp/ocsp_vfy.c
    - name: more crypto/ocsp/v3_ocsp.c
      run: more crypto/ocsp/v3_ocsp.c
    - name: more crypto/mem.c
      run: more crypto/mem.c
    - name: Maven and co make
      run: make
    - name: ls -l
      run: ls -l
    - name: ls -l apps
      run: ls -l apps
    - name: ls -l crypto
      run: ls -l crypto
    - name: make test01
      # run: make test 2> ./make_test_err.log
      # V=1 : mode verbose
      run: make V=1 TESTS=01 test 2>> ./make_test_err01.log
    - name: make test02
      run: make V=1 TESTS=02 test 2>> ./make_test_err02.log
    - name: make test03
      run: make V=1 TESTS=03 test 2>> ./make_test_err03.log
    - name: make test04
      run: make V=1 TESTS=04 test 2>> ./make_test_err04.log
    - name: make test05
      run: make V=1 TESTS=05 test 2>> ./make_test_err05.log
    - name: make test06
      run: make V=1 TESTS=06 test 2>> ./make_test_err06.log
    - name: make test07
      run: make V=1 TESTS=07 test 2>> ./make_test_err07.log
    - name: make test08
      run: make V=1 TESTS=08 test 2>> ./make_test_err08.log
    - name: make test09
      run: make V=1 TESTS=09 test 2>> ./make_test_err09.log
    - name: make test99
      run: make V=1 TESTS=99 test 2>> ./make_test_err99.log
    - name: ls -l 
      run: ls -l 
    - name: ls -lR 
      run: ls -lR "$PWD/"*
    - name: Maven and co sort
      run: sort -u -o make_test_err_sort.log make_test_err*.log
    - name: ls
      run: ls -l make_test_err_sort.log
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-sauve-log
        path: make_test_err_sort.log
    - uses: actions/upload-artifact@v2
      with:
        name: ArtifactTestRuns
        path: |
           test-runs
           !test-runs/**/*:*
    - name: Run maven site
      run: mvn site -Dsonar.reporting01nodocgeneration=yes
    - uses: actions/upload-artifact@v2
      with:
        name: ArtifactMvnSite
        path: |
           target/site
