name: C/C++ CI Complet

on:
  [push]
jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: lister
      run: ls
    - name: Verif maven
      run: mvn -U clean
    - name: lister
      run: ls
    - name: configure avec generation des template seul
      run: ./config -no-asm -E
    - name: make depend
      run: make depend
    - name: make
      run: make
    - name: Maven and co qcrgoalfileclonecpp
      run: mvn -U qcr:qcrgoalfileclonecpp
    - name: Maven and co compile
      run: mvn qcr:qcrgoalcompile
    - name: Maven and co
      run: mvn qcr:qcrgoalfilecopycpp
    - name: Maven and co
      run: mvn clean
    - name: Maven and co
      run: ls # ne sert plus depuis 2019 12 29 cat secucpp/qcrutils.c >> crypto/cryptlib.c
    - name: Maven and co
      run: ls # ne sert plus depuis 2019 12 29 cat secucpp/qcrutils.c >> apps/openssl.c
    - name: Maven and co
      run: ls # ne sert plus depuis 2019 12 29 cat secucpp/qcrutils.c >> fuzz/test-corpus.c
    - name: Maven and co
      run: ls # ne sert plus depuis 2019 12 29 rm  secucpp/qcrutils.c
    - name: Maven and co
      run: ./config -no-asm
    - name: Maven and co
      run: make depend
    - name: Maven and co
      run: rm -f /openssl/test/*.o
    - name: Maven and co
      run: make
    - name: make test
      run: make test 2> ./make_test_err.log
    - name: Maven and co
      run: sort -u -o make_test_err_sort.log make_test_err.log
