@startuml
!pragma layout smetana
class dummy {
getchar(void) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#769]]]
fgetc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#778]]]
getc_unlocked(FILE*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#788]]]
getchar_unlocked(void) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#795]]]
putchar(int) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#804]]]
fputc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#813]]]
putc_unlocked(int;FILE*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#823]]]
putchar_unlocked(int) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#830]]]
feof_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#836]]]
ferror_unlocked(FILE*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#843]]]
sprintf(char*;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#862]]]
vsprintf(char*;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#875]]]
snprintf(char*;size_t;char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#894]]]
vsnprintf(char*;size_t;char*;__gnuc_va_list) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#908]]]
fprintf(FILE*;char*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#929]]]
printf(char*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#936]]]
vprintf(char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#948]]]
vfprintf(FILE*;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#958]]]
dprintf(int;char*) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#973]]]
vdprintf(int;char*;__gnuc_va_list) :  int  [[[./../../.././qc/crypto/cmac/cmac.c.html#984]]]
fgets(char*;int;FILE*) :  char  [[[./../../.././qc/crypto/cmac/cmac.c.html#1003]]]
fread(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1029]]]
fread_unlocked(void*;size_t;size_t;FILE*) : size_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1056]]]
atoi(char*) :  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#1216]]]
atol(char*) :  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#1221]]]
atoll(char*) :  long  long  int  __attribute__ (( __nothrow__ ,__leaf__)) [[[./../../.././qc/crypto/cmac/cmac.c.html#1228]]]
__bswap_16(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1381]]]
__bswap_32(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1396]]]
__bswap_64(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1406]]]
__uint16_identity(__uint16_t) : __uint16_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1418]]]
__uint32_identity(__uint32_t) : __uint32_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1424]]]
__uint64_identity(__uint64_t) : __uint64_t [[[./../../.././qc/crypto/cmac/cmac.c.html#1430]]]
bsearch(void*;void*;size_t;size_t;__compar_fn_t) :  void  [[[./../../.././qc/crypto/cmac/cmac.c.html#2098]]]
} 
@enduml
